version: "3.9"

services:
    dashboard:
        oceanops-api: oceanops-api
        image: oceanops-api
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        environment:
            JAVA_OPTIONS: "--add-exports java.base/sun.security.action=ALL-UNNAMED -Duser.timezone=UTC -Dcayenne.jdbc.driver=${DB_DRIVER} -Dcayenne.jdbc.url=${DB_URL} -Dcayenne.jdbc.username=${DB_USERNAME} -Dcayenne.jdbc.password=${DB_PASSWORD}"
        networks:
            - oceanops-network

networks:
  oceanops-network:
    name: oceanops-network
 