version: "3.9"

services:
    oceanops-api-main:
        container_name: oceanops-api-main
        image: oceanops-api-main
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
        environment:
            JAVA_OPTIONS: "-Duser.timezone=UTC -Dcayenne.jdbc.driver=${DB_DRIVER} -Dcayenne.jdbc.url=${DB_URL} -Dcayenne.jdbc.username=${DB_USERNAME} -Dcayenne.jdbc.password=${DB_PASSWORD}"
        networks:
            - oceanops-bridge-network

networks:
    oceanops-bridge-network: 
        name: oceanops-bridge-network
        external: true
 