package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;

/**
 * Class _IndicatorValue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _IndicatorValue extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final DateProperty<LocalDateTime> END_DATE = PropertyFactory.createDate("endDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> ID = PropertyFactory.createNumeric("id", BigDecimal.class);
    public static final NumericProperty<BigDecimal> INDICATOR_ID = PropertyFactory.createNumeric("indicatorId", BigDecimal.class);
    public static final DateProperty<LocalDateTime> START_DATE = PropertyFactory.createDate("startDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> VALUE = PropertyFactory.createNumeric("value", BigDecimal.class);
    public static final NumericProperty<BigDecimal> VALUE_RAW = PropertyFactory.createNumeric("valueRaw", BigDecimal.class);

    protected LocalDateTime endDate;
    protected BigDecimal id;
    protected BigDecimal indicatorId;
    protected LocalDateTime startDate;
    protected BigDecimal value;
    protected BigDecimal valueRaw;


    public void setEndDate(LocalDateTime endDate) {
        beforePropertyWrite("endDate", this.endDate, endDate);
        this.endDate = endDate;
    }

    public LocalDateTime getEndDate() {
        beforePropertyRead("endDate");
        return this.endDate;
    }

    public void setId(BigDecimal id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public BigDecimal getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setIndicatorId(BigDecimal indicatorId) {
        beforePropertyWrite("indicatorId", this.indicatorId, indicatorId);
        this.indicatorId = indicatorId;
    }

    public BigDecimal getIndicatorId() {
        beforePropertyRead("indicatorId");
        return this.indicatorId;
    }

    public void setStartDate(LocalDateTime startDate) {
        beforePropertyWrite("startDate", this.startDate, startDate);
        this.startDate = startDate;
    }

    public LocalDateTime getStartDate() {
        beforePropertyRead("startDate");
        return this.startDate;
    }

    public void setValue(BigDecimal value) {
        beforePropertyWrite("value", this.value, value);
        this.value = value;
    }

    public BigDecimal getValue() {
        beforePropertyRead("value");
        return this.value;
    }

    public void setValueRaw(BigDecimal valueRaw) {
        beforePropertyWrite("valueRaw", this.valueRaw, valueRaw);
        this.valueRaw = valueRaw;
    }

    public BigDecimal getValueRaw() {
        beforePropertyRead("valueRaw");
        return this.valueRaw;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "endDate":
                return this.endDate;
            case "id":
                return this.id;
            case "indicatorId":
                return this.indicatorId;
            case "startDate":
                return this.startDate;
            case "value":
                return this.value;
            case "valueRaw":
                return this.valueRaw;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "endDate":
                this.endDate = (LocalDateTime)val;
                break;
            case "id":
                this.id = (BigDecimal)val;
                break;
            case "indicatorId":
                this.indicatorId = (BigDecimal)val;
                break;
            case "startDate":
                this.startDate = (LocalDateTime)val;
                break;
            case "value":
                this.value = (BigDecimal)val;
                break;
            case "valueRaw":
                this.valueRaw = (BigDecimal)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.endDate);
        out.writeObject(this.id);
        out.writeObject(this.indicatorId);
        out.writeObject(this.startDate);
        out.writeObject(this.value);
        out.writeObject(this.valueRaw);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.endDate = (LocalDateTime)in.readObject();
        this.id = (BigDecimal)in.readObject();
        this.indicatorId = (BigDecimal)in.readObject();
        this.startDate = (LocalDateTime)in.readObject();
        this.value = (BigDecimal)in.readObject();
        this.valueRaw = (BigDecimal)in.readObject();
    }

}
