package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.api.orm.Ptf;

/**
 * Class _ObsLatest was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ObsLatest extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<BigDecimal> ID = PropertyFactory.createNumeric("id", BigDecimal.class);
    public static final NumericProperty<BigDecimal> LAT = PropertyFactory.createNumeric("lat", BigDecimal.class);
    public static final NumericProperty<BigDecimal> LON = PropertyFactory.createNumeric("lon", BigDecimal.class);
    public static final DateProperty<LocalDateTime> OBS_DATE = PropertyFactory.createDate("obsDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> ORIGIN_ID = PropertyFactory.createNumeric("originId", BigDecimal.class);
    public static final StringProperty<String> ORIGIN_TABLE = PropertyFactory.createString("originTable", String.class);
    public static final BaseProperty<byte[]> SHAPE = PropertyFactory.createBase("shape", byte[].class);
    public static final ListProperty<Ptf> PTFS = PropertyFactory.createList("ptfs", Ptf.class);

    protected BigDecimal id;
    protected BigDecimal lat;
    protected BigDecimal lon;
    protected LocalDateTime obsDate;
    protected BigDecimal originId;
    protected String originTable;
    protected byte[] shape;

    protected Object ptfs;

    public void setId(BigDecimal id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public BigDecimal getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setLat(BigDecimal lat) {
        beforePropertyWrite("lat", this.lat, lat);
        this.lat = lat;
    }

    public BigDecimal getLat() {
        beforePropertyRead("lat");
        return this.lat;
    }

    public void setLon(BigDecimal lon) {
        beforePropertyWrite("lon", this.lon, lon);
        this.lon = lon;
    }

    public BigDecimal getLon() {
        beforePropertyRead("lon");
        return this.lon;
    }

    public void setObsDate(LocalDateTime obsDate) {
        beforePropertyWrite("obsDate", this.obsDate, obsDate);
        this.obsDate = obsDate;
    }

    public LocalDateTime getObsDate() {
        beforePropertyRead("obsDate");
        return this.obsDate;
    }

    public void setOriginId(BigDecimal originId) {
        beforePropertyWrite("originId", this.originId, originId);
        this.originId = originId;
    }

    public BigDecimal getOriginId() {
        beforePropertyRead("originId");
        return this.originId;
    }

    public void setOriginTable(String originTable) {
        beforePropertyWrite("originTable", this.originTable, originTable);
        this.originTable = originTable;
    }

    public String getOriginTable() {
        beforePropertyRead("originTable");
        return this.originTable;
    }

    public void setShape(byte[] shape) {
        beforePropertyWrite("shape", this.shape, shape);
        this.shape = shape;
    }

    public byte[] getShape() {
        beforePropertyRead("shape");
        return this.shape;
    }

    public void addToPtfs(Ptf obj) {
        addToManyTarget("ptfs", obj, true);
    }

    public void removeFromPtfs(Ptf obj) {
        removeToManyTarget("ptfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Ptf> getPtfs() {
        return (List<Ptf>)readProperty("ptfs");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "id":
                return this.id;
            case "lat":
                return this.lat;
            case "lon":
                return this.lon;
            case "obsDate":
                return this.obsDate;
            case "originId":
                return this.originId;
            case "originTable":
                return this.originTable;
            case "shape":
                return this.shape;
            case "ptfs":
                return this.ptfs;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "id":
                this.id = (BigDecimal)val;
                break;
            case "lat":
                this.lat = (BigDecimal)val;
                break;
            case "lon":
                this.lon = (BigDecimal)val;
                break;
            case "obsDate":
                this.obsDate = (LocalDateTime)val;
                break;
            case "originId":
                this.originId = (BigDecimal)val;
                break;
            case "originTable":
                this.originTable = (String)val;
                break;
            case "shape":
                this.shape = (byte[])val;
                break;
            case "ptfs":
                this.ptfs = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.id);
        out.writeObject(this.lat);
        out.writeObject(this.lon);
        out.writeObject(this.obsDate);
        out.writeObject(this.originId);
        out.writeObject(this.originTable);
        out.writeObject(this.shape);
        out.writeObject(this.ptfs);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.id = (BigDecimal)in.readObject();
        this.lat = (BigDecimal)in.readObject();
        this.lon = (BigDecimal)in.readObject();
        this.obsDate = (LocalDateTime)in.readObject();
        this.originId = (BigDecimal)in.readObject();
        this.originTable = (String)in.readObject();
        this.shape = (byte[])in.readObject();
        this.ptfs = in.readObject();
    }

}
