package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.api.orm.Obs;
import org.oceanops.api.orm.VariableSub;

/**
 * Class _ObsVariableSub was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ObsVariableSub extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String OBS_ID_PK_COLUMN = "OBS_ID";
    public static final String VARIABLE_SUB_ID_PK_COLUMN = "VARIABLE_SUB_ID";

    public static final NumericProperty<BigDecimal> DEPTH = PropertyFactory.createNumeric("depth", BigDecimal.class);
    public static final NumericProperty<BigDecimal> LEVELS_NB = PropertyFactory.createNumeric("levelsNb", BigDecimal.class);
    public static final NumericProperty<BigDecimal> OBS_ID = PropertyFactory.createNumeric("obsId", BigDecimal.class);
    public static final StringProperty<String> QC = PropertyFactory.createString("qc", String.class);
    public static final NumericProperty<BigDecimal> VARIABLE_SUB_ID = PropertyFactory.createNumeric("variableSubId", BigDecimal.class);
    public static final EntityProperty<Obs> OBS = PropertyFactory.createEntity("obs", Obs.class);
    public static final EntityProperty<VariableSub> VARIABLE_SUB = PropertyFactory.createEntity("variableSub", VariableSub.class);

    protected BigDecimal depth;
    protected BigDecimal levelsNb;
    protected BigDecimal obsId;
    protected String qc;
    protected BigDecimal variableSubId;

    protected Object obs;
    protected Object variableSub;

    public void setDepth(BigDecimal depth) {
        beforePropertyWrite("depth", this.depth, depth);
        this.depth = depth;
    }

    public BigDecimal getDepth() {
        beforePropertyRead("depth");
        return this.depth;
    }

    public void setLevelsNb(BigDecimal levelsNb) {
        beforePropertyWrite("levelsNb", this.levelsNb, levelsNb);
        this.levelsNb = levelsNb;
    }

    public BigDecimal getLevelsNb() {
        beforePropertyRead("levelsNb");
        return this.levelsNb;
    }

    public void setObsId(BigDecimal obsId) {
        beforePropertyWrite("obsId", this.obsId, obsId);
        this.obsId = obsId;
    }

    public BigDecimal getObsId() {
        beforePropertyRead("obsId");
        return this.obsId;
    }

    public void setQc(String qc) {
        beforePropertyWrite("qc", this.qc, qc);
        this.qc = qc;
    }

    public String getQc() {
        beforePropertyRead("qc");
        return this.qc;
    }

    public void setVariableSubId(BigDecimal variableSubId) {
        beforePropertyWrite("variableSubId", this.variableSubId, variableSubId);
        this.variableSubId = variableSubId;
    }

    public BigDecimal getVariableSubId() {
        beforePropertyRead("variableSubId");
        return this.variableSubId;
    }

    public void setObs(Obs obs) {
        setToOneTarget("obs", obs, true);
    }

    public Obs getObs() {
        return (Obs)readProperty("obs");
    }

    public void setVariableSub(VariableSub variableSub) {
        setToOneTarget("variableSub", variableSub, true);
    }

    public VariableSub getVariableSub() {
        return (VariableSub)readProperty("variableSub");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "depth":
                return this.depth;
            case "levelsNb":
                return this.levelsNb;
            case "obsId":
                return this.obsId;
            case "qc":
                return this.qc;
            case "variableSubId":
                return this.variableSubId;
            case "obs":
                return this.obs;
            case "variableSub":
                return this.variableSub;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "depth":
                this.depth = (BigDecimal)val;
                break;
            case "levelsNb":
                this.levelsNb = (BigDecimal)val;
                break;
            case "obsId":
                this.obsId = (BigDecimal)val;
                break;
            case "qc":
                this.qc = (String)val;
                break;
            case "variableSubId":
                this.variableSubId = (BigDecimal)val;
                break;
            case "obs":
                this.obs = val;
                break;
            case "variableSub":
                this.variableSub = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.depth);
        out.writeObject(this.levelsNb);
        out.writeObject(this.obsId);
        out.writeObject(this.qc);
        out.writeObject(this.variableSubId);
        out.writeObject(this.obs);
        out.writeObject(this.variableSub);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.depth = (BigDecimal)in.readObject();
        this.levelsNb = (BigDecimal)in.readObject();
        this.obsId = (BigDecimal)in.readObject();
        this.qc = (String)in.readObject();
        this.variableSubId = (BigDecimal)in.readObject();
        this.obs = in.readObject();
        this.variableSub = in.readObject();
    }

}
