package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.api.orm.Obs;
import org.oceanops.api.orm.Variable;

/**
 * Class _ObsVariable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ObsVariable extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String OBS_ID_PK_COLUMN = "OBS_ID";
    public static final String VARIABLE_ID_PK_COLUMN = "VARIABLE_ID";

    public static final NumericProperty<BigDecimal> ADJUSTMENT_DEVIATION = PropertyFactory.createNumeric("adjustmentDeviation", BigDecimal.class);
    public static final NumericProperty<BigDecimal> ADJUSTMENT_MEAN = PropertyFactory.createNumeric("adjustmentMean", BigDecimal.class);
    public static final NumericProperty<BigDecimal> DEPTH = PropertyFactory.createNumeric("depth", BigDecimal.class);
    public static final NumericProperty<BigDecimal> LEVELS_NB = PropertyFactory.createNumeric("levelsNb", BigDecimal.class);
    public static final NumericProperty<BigDecimal> OBS_ID = PropertyFactory.createNumeric("obsId", BigDecimal.class);
    public static final StringProperty<String> QC = PropertyFactory.createString("qc", String.class);
    public static final NumericProperty<BigDecimal> VARIABLE_ID = PropertyFactory.createNumeric("variableId", BigDecimal.class);
    public static final EntityProperty<Obs> OBS = PropertyFactory.createEntity("obs", Obs.class);
    public static final EntityProperty<Variable> VARIABLE = PropertyFactory.createEntity("variable", Variable.class);

    protected BigDecimal adjustmentDeviation;
    protected BigDecimal adjustmentMean;
    protected BigDecimal depth;
    protected BigDecimal levelsNb;
    protected BigDecimal obsId;
    protected String qc;
    protected BigDecimal variableId;

    protected Object obs;
    protected Object variable;

    public void setAdjustmentDeviation(BigDecimal adjustmentDeviation) {
        beforePropertyWrite("adjustmentDeviation", this.adjustmentDeviation, adjustmentDeviation);
        this.adjustmentDeviation = adjustmentDeviation;
    }

    public BigDecimal getAdjustmentDeviation() {
        beforePropertyRead("adjustmentDeviation");
        return this.adjustmentDeviation;
    }

    public void setAdjustmentMean(BigDecimal adjustmentMean) {
        beforePropertyWrite("adjustmentMean", this.adjustmentMean, adjustmentMean);
        this.adjustmentMean = adjustmentMean;
    }

    public BigDecimal getAdjustmentMean() {
        beforePropertyRead("adjustmentMean");
        return this.adjustmentMean;
    }

    public void setDepth(BigDecimal depth) {
        beforePropertyWrite("depth", this.depth, depth);
        this.depth = depth;
    }

    public BigDecimal getDepth() {
        beforePropertyRead("depth");
        return this.depth;
    }

    public void setLevelsNb(BigDecimal levelsNb) {
        beforePropertyWrite("levelsNb", this.levelsNb, levelsNb);
        this.levelsNb = levelsNb;
    }

    public BigDecimal getLevelsNb() {
        beforePropertyRead("levelsNb");
        return this.levelsNb;
    }

    public void setObsId(BigDecimal obsId) {
        beforePropertyWrite("obsId", this.obsId, obsId);
        this.obsId = obsId;
    }

    public BigDecimal getObsId() {
        beforePropertyRead("obsId");
        return this.obsId;
    }

    public void setQc(String qc) {
        beforePropertyWrite("qc", this.qc, qc);
        this.qc = qc;
    }

    public String getQc() {
        beforePropertyRead("qc");
        return this.qc;
    }

    public void setVariableId(BigDecimal variableId) {
        beforePropertyWrite("variableId", this.variableId, variableId);
        this.variableId = variableId;
    }

    public BigDecimal getVariableId() {
        beforePropertyRead("variableId");
        return this.variableId;
    }

    public void setObs(Obs obs) {
        setToOneTarget("obs", obs, true);
    }

    public Obs getObs() {
        return (Obs)readProperty("obs");
    }

    public void setVariable(Variable variable) {
        setToOneTarget("variable", variable, true);
    }

    public Variable getVariable() {
        return (Variable)readProperty("variable");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "adjustmentDeviation":
                return this.adjustmentDeviation;
            case "adjustmentMean":
                return this.adjustmentMean;
            case "depth":
                return this.depth;
            case "levelsNb":
                return this.levelsNb;
            case "obsId":
                return this.obsId;
            case "qc":
                return this.qc;
            case "variableId":
                return this.variableId;
            case "obs":
                return this.obs;
            case "variable":
                return this.variable;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "adjustmentDeviation":
                this.adjustmentDeviation = (BigDecimal)val;
                break;
            case "adjustmentMean":
                this.adjustmentMean = (BigDecimal)val;
                break;
            case "depth":
                this.depth = (BigDecimal)val;
                break;
            case "levelsNb":
                this.levelsNb = (BigDecimal)val;
                break;
            case "obsId":
                this.obsId = (BigDecimal)val;
                break;
            case "qc":
                this.qc = (String)val;
                break;
            case "variableId":
                this.variableId = (BigDecimal)val;
                break;
            case "obs":
                this.obs = val;
                break;
            case "variable":
                this.variable = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.adjustmentDeviation);
        out.writeObject(this.adjustmentMean);
        out.writeObject(this.depth);
        out.writeObject(this.levelsNb);
        out.writeObject(this.obsId);
        out.writeObject(this.qc);
        out.writeObject(this.variableId);
        out.writeObject(this.obs);
        out.writeObject(this.variable);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.adjustmentDeviation = (BigDecimal)in.readObject();
        this.adjustmentMean = (BigDecimal)in.readObject();
        this.depth = (BigDecimal)in.readObject();
        this.levelsNb = (BigDecimal)in.readObject();
        this.obsId = (BigDecimal)in.readObject();
        this.qc = (String)in.readObject();
        this.variableId = (BigDecimal)in.readObject();
        this.obs = in.readObject();
        this.variable = in.readObject();
    }

}
