package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.api.orm.AgencyPtf;
import org.oceanops.api.orm.ContactPtfRole;
import org.oceanops.api.orm.DataStatus;
import org.oceanops.api.orm.Doc;
import org.oceanops.api.orm.EndingCause;
import org.oceanops.api.orm.GliderThemePtf;
import org.oceanops.api.orm.Line;
import org.oceanops.api.orm.LocSystem;
import org.oceanops.api.orm.MzmsPtfCountry;
import org.oceanops.api.orm.NcNotification;
import org.oceanops.api.orm.NcSubscription;
import org.oceanops.api.orm.NetworkPtf;
import org.oceanops.api.orm.Obs;
import org.oceanops.api.orm.ObsArgoGdac;
import org.oceanops.api.orm.ObsGlidersGtsOsmc;
import org.oceanops.api.orm.ObsLatest;
import org.oceanops.api.orm.ObsTsunaGtsOsmc;
import org.oceanops.api.orm.Program;
import org.oceanops.api.orm.PtfAutomation;
import org.oceanops.api.orm.PtfCategory;
import org.oceanops.api.orm.PtfConfig;
import org.oceanops.api.orm.PtfCruise;
import org.oceanops.api.orm.PtfDeployment;
import org.oceanops.api.orm.PtfHardware;
import org.oceanops.api.orm.PtfIdentifiers;
import org.oceanops.api.orm.PtfInspection;
import org.oceanops.api.orm.PtfLoc;
import org.oceanops.api.orm.PtfLocStatus;
import org.oceanops.api.orm.PtfModel;
import org.oceanops.api.orm.PtfPtfStatus;
import org.oceanops.api.orm.PtfSoftware;
import org.oceanops.api.orm.PtfStatistics;
import org.oceanops.api.orm.PtfStatus;
import org.oceanops.api.orm.PtfVariable;
import org.oceanops.api.orm.PtfVariableSub;
import org.oceanops.api.orm.QcFeedback;
import org.oceanops.api.orm.Retrieval;
import org.oceanops.api.orm.Service;
import org.oceanops.api.orm.SitePtf;
import org.oceanops.api.orm.Telecom;
import org.oceanops.api.orm.WebFrequentation;
import org.oceanops.api.orm.Weblink;
import org.oceanops.api.orm.WeblinkPtf;
import org.oceanops.api.orm.Wmo;

/**
 * Class _Ptf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Ptf extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final NumericProperty<BigDecimal> ACTIVITY_CRITERION = PropertyFactory.createNumeric("activityCriterion", BigDecimal.class);
    public static final NumericProperty<BigDecimal> AGE = PropertyFactory.createNumeric("age", BigDecimal.class);
    public static final NumericProperty<BigDecimal> AGE_WEIGHT = PropertyFactory.createNumeric("ageWeight", BigDecimal.class);
    public static final NumericProperty<BigDecimal> CLOSURE_CRITERION = PropertyFactory.createNumeric("closureCriterion", BigDecimal.class);
    public static final StringProperty<String> DATA_URL = PropertyFactory.createString("dataUrl", String.class);
    public static final NumericProperty<BigDecimal> DELETE_TAG = PropertyFactory.createNumeric("deleteTag", BigDecimal.class);
    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final DateProperty<LocalDateTime> E_NOTIFICATION_DATE = PropertyFactory.createDate("eNotificationDate", LocalDateTime.class);
    public static final DateProperty<LocalDateTime> ENDING_DATE = PropertyFactory.createDate("endingDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> ID = PropertyFactory.createNumeric("id", BigDecimal.class);
    public static final DateProperty<LocalDateTime> INSERT_DATE = PropertyFactory.createDate("insertDate", LocalDateTime.class);
    public static final DateProperty<LocalDateTime> LAST_UPDATE = PropertyFactory.createDate("lastUpdate", LocalDateTime.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> NOK_REASON = PropertyFactory.createString("nokReason", String.class);
    public static final StringProperty<String> REF = PropertyFactory.createString("ref", String.class);
    public static final StringProperty<String> REF_PARENT = PropertyFactory.createString("refParent", String.class);
    public static final DateProperty<LocalDateTime> UPDATE_DATE = PropertyFactory.createDate("updateDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> VALIDATED = PropertyFactory.createNumeric("validated", BigDecimal.class);
    public static final ListProperty<AgencyPtf> AGENCY_PTFS = PropertyFactory.createList("agencyPtfs", AgencyPtf.class);
    public static final EntityProperty<Telecom> BACKUP_TELECOM = PropertyFactory.createEntity("backupTelecom", Telecom.class);
    public static final EntityProperty<LocSystem> BACKUP_TRACKING_SYSTEM = PropertyFactory.createEntity("backupTrackingSystem", LocSystem.class);
    public static final ListProperty<ContactPtfRole> CONTACT_PTF_ROLES = PropertyFactory.createList("contactPtfRoles", ContactPtfRole.class);
    public static final EntityProperty<DataStatus> DATA_STATUS = PropertyFactory.createEntity("dataStatus", DataStatus.class);
    public static final EntityProperty<Doc> DOC = PropertyFactory.createEntity("doc", Doc.class);
    public static final ListProperty<Doc> DOCS = PropertyFactory.createList("docs", Doc.class);
    public static final EntityProperty<EndingCause> ENDING_CAUSE = PropertyFactory.createEntity("endingCause", EndingCause.class);
    public static final ListProperty<GliderThemePtf> GLIDER_THEME_PTFS = PropertyFactory.createList("gliderThemePtfs", GliderThemePtf.class);
    public static final EntityProperty<ObsLatest> LATEST_OBS = PropertyFactory.createEntity("latestObs", ObsLatest.class);
    public static final ListProperty<Line> LINES = PropertyFactory.createList("lines", Line.class);
    public static final ListProperty<MzmsPtfCountry> MZMS_PTF_COUNTRIES = PropertyFactory.createList("mzmsPtfCountries", MzmsPtfCountry.class);
    public static final ListProperty<NcNotification> NC_NOTIFICATIONS = PropertyFactory.createList("ncNotifications", NcNotification.class);
    public static final ListProperty<NcSubscription> NC_SUBSCRIPTIONS = PropertyFactory.createList("ncSubscriptions", NcSubscription.class);
    public static final ListProperty<NetworkPtf> NETWORK_PTFS = PropertyFactory.createList("networkPtfs", NetworkPtf.class);
    public static final ListProperty<ObsArgoGdac> OBS_ARGO_GDACS = PropertyFactory.createList("obsArgoGdacs", ObsArgoGdac.class);
    public static final ListProperty<ObsGlidersGtsOsmc> OBS_GLIDERS_GTS_OSMCS = PropertyFactory.createList("obsGlidersGtsOsmcs", ObsGlidersGtsOsmc.class);
    public static final ListProperty<ObsTsunaGtsOsmc> OBS_TSUNA_GTS_OSMCS = PropertyFactory.createList("obsTsunaGtsOsmcs", ObsTsunaGtsOsmc.class);
    public static final ListProperty<Obs> OBSS = PropertyFactory.createList("obss", Obs.class);
    public static final EntityProperty<Program> PROGRAM = PropertyFactory.createEntity("program", Program.class);
    public static final EntityProperty<PtfAutomation> PTF_AUTOMATION = PropertyFactory.createEntity("ptfAutomation", PtfAutomation.class);
    public static final ListProperty<PtfCategory> PTF_CATEGORIES = PropertyFactory.createList("ptfCategories", PtfCategory.class);
    public static final ListProperty<PtfConfig> PTF_CONFIGS = PropertyFactory.createList("ptfConfigs", PtfConfig.class);
    public static final ListProperty<PtfCruise> PTF_CRUISES = PropertyFactory.createList("ptfCruises", PtfCruise.class);
    public static final EntityProperty<PtfDeployment> PTF_DEPL = PropertyFactory.createEntity("ptfDepl", PtfDeployment.class);
    public static final EntityProperty<PtfHardware> PTF_HARDWARE = PropertyFactory.createEntity("ptfHardware", PtfHardware.class);
    public static final EntityProperty<PtfIdentifiers> PTF_IDENTIFIERS = PropertyFactory.createEntity("ptfIdentifiers", PtfIdentifiers.class);
    public static final EntityProperty<PtfInspection> PTF_INSPECTION = PropertyFactory.createEntity("ptfInspection", PtfInspection.class);
    public static final ListProperty<PtfLocStatus> PTF_LOC_STATUSES = PropertyFactory.createList("ptfLocStatuses", PtfLocStatus.class);
    public static final ListProperty<PtfLoc> PTF_LOCS = PropertyFactory.createList("ptfLocs", PtfLoc.class);
    public static final EntityProperty<PtfModel> PTF_MODEL = PropertyFactory.createEntity("ptfModel", PtfModel.class);
    public static final ListProperty<PtfPtfStatus> PTF_PTF_STATUSES = PropertyFactory.createList("ptfPtfStatuses", PtfPtfStatus.class);
    public static final EntityProperty<PtfSoftware> PTF_SOFTWARE = PropertyFactory.createEntity("ptfSoftware", PtfSoftware.class);
    public static final EntityProperty<PtfStatistics> PTF_STATISTICS = PropertyFactory.createEntity("ptfStatistics", PtfStatistics.class);
    public static final EntityProperty<PtfStatus> PTF_STATUS = PropertyFactory.createEntity("ptfStatus", PtfStatus.class);
    public static final ListProperty<PtfVariableSub> PTF_VARIABLE_SUBS = PropertyFactory.createList("ptfVariableSubs", PtfVariableSub.class);
    public static final ListProperty<PtfVariable> PTF_VARIABLES = PropertyFactory.createList("ptfVariables", PtfVariable.class);
    public static final ListProperty<QcFeedback> QC_FEEDBACKS = PropertyFactory.createList("qcFeedbacks", QcFeedback.class);
    public static final EntityProperty<Retrieval> RETRIEVAL = PropertyFactory.createEntity("retrieval", Retrieval.class);
    public static final ListProperty<Service> SERVICES = PropertyFactory.createList("services", Service.class);
    public static final ListProperty<SitePtf> SITE_PTFS = PropertyFactory.createList("sitePtfs", SitePtf.class);
    public static final EntityProperty<Telecom> TELECOM = PropertyFactory.createEntity("telecom", Telecom.class);
    public static final EntityProperty<LocSystem> TRACKING_SYSTEM = PropertyFactory.createEntity("trackingSystem", LocSystem.class);
    public static final ListProperty<WebFrequentation> WEB_FREQUENTATIONS = PropertyFactory.createList("webFrequentations", WebFrequentation.class);
    public static final ListProperty<WeblinkPtf> WEBLINK_PTFS = PropertyFactory.createList("weblinkPtfs", WeblinkPtf.class);
    public static final ListProperty<Weblink> WEBLINKS = PropertyFactory.createList("weblinks", Weblink.class);
    public static final ListProperty<Wmo> WMOS = PropertyFactory.createList("wmos", Wmo.class);

    protected BigDecimal activityCriterion;
    protected BigDecimal age;
    protected BigDecimal ageWeight;
    protected BigDecimal closureCriterion;
    protected String dataUrl;
    protected BigDecimal deleteTag;
    protected String description;
    protected LocalDateTime eNotificationDate;
    protected LocalDateTime endingDate;
    protected BigDecimal id;
    protected LocalDateTime insertDate;
    protected LocalDateTime lastUpdate;
    protected String name;
    protected String nokReason;
    protected String ref;
    protected String refParent;
    protected LocalDateTime updateDate;
    protected BigDecimal validated;

    protected Object agencyPtfs;
    protected Object backupTelecom;
    protected Object backupTrackingSystem;
    protected Object contactPtfRoles;
    protected Object dataStatus;
    protected Object doc;
    protected Object docs;
    protected Object endingCause;
    protected Object gliderThemePtfs;
    protected Object latestObs;
    protected Object lines;
    protected Object mzmsPtfCountries;
    protected Object ncNotifications;
    protected Object ncSubscriptions;
    protected Object networkPtfs;
    protected Object obsArgoGdacs;
    protected Object obsGlidersGtsOsmcs;
    protected Object obsTsunaGtsOsmcs;
    protected Object obss;
    protected Object program;
    protected Object ptfAutomation;
    protected Object ptfCategories;
    protected Object ptfConfigs;
    protected Object ptfCruises;
    protected Object ptfDepl;
    protected Object ptfHardware;
    protected Object ptfIdentifiers;
    protected Object ptfInspection;
    protected Object ptfLocStatuses;
    protected Object ptfLocs;
    protected Object ptfModel;
    protected Object ptfPtfStatuses;
    protected Object ptfSoftware;
    protected Object ptfStatistics;
    protected Object ptfStatus;
    protected Object ptfVariableSubs;
    protected Object ptfVariables;
    protected Object qcFeedbacks;
    protected Object retrieval;
    protected Object services;
    protected Object sitePtfs;
    protected Object telecom;
    protected Object trackingSystem;
    protected Object webFrequentations;
    protected Object weblinkPtfs;
    protected Object weblinks;
    protected Object wmos;

    public void setActivityCriterion(BigDecimal activityCriterion) {
        beforePropertyWrite("activityCriterion", this.activityCriterion, activityCriterion);
        this.activityCriterion = activityCriterion;
    }

    public BigDecimal getActivityCriterion() {
        beforePropertyRead("activityCriterion");
        return this.activityCriterion;
    }

    public void setAge(BigDecimal age) {
        beforePropertyWrite("age", this.age, age);
        this.age = age;
    }

    public BigDecimal getAge() {
        beforePropertyRead("age");
        return this.age;
    }

    public void setAgeWeight(BigDecimal ageWeight) {
        beforePropertyWrite("ageWeight", this.ageWeight, ageWeight);
        this.ageWeight = ageWeight;
    }

    public BigDecimal getAgeWeight() {
        beforePropertyRead("ageWeight");
        return this.ageWeight;
    }

    public void setClosureCriterion(BigDecimal closureCriterion) {
        beforePropertyWrite("closureCriterion", this.closureCriterion, closureCriterion);
        this.closureCriterion = closureCriterion;
    }

    public BigDecimal getClosureCriterion() {
        beforePropertyRead("closureCriterion");
        return this.closureCriterion;
    }

    public void setDataUrl(String dataUrl) {
        beforePropertyWrite("dataUrl", this.dataUrl, dataUrl);
        this.dataUrl = dataUrl;
    }

    public String getDataUrl() {
        beforePropertyRead("dataUrl");
        return this.dataUrl;
    }

    public void setDeleteTag(BigDecimal deleteTag) {
        beforePropertyWrite("deleteTag", this.deleteTag, deleteTag);
        this.deleteTag = deleteTag;
    }

    public BigDecimal getDeleteTag() {
        beforePropertyRead("deleteTag");
        return this.deleteTag;
    }

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String getDescription() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setENotificationDate(LocalDateTime eNotificationDate) {
        beforePropertyWrite("eNotificationDate", this.eNotificationDate, eNotificationDate);
        this.eNotificationDate = eNotificationDate;
    }

    public LocalDateTime getENotificationDate() {
        beforePropertyRead("eNotificationDate");
        return this.eNotificationDate;
    }

    public void setEndingDate(LocalDateTime endingDate) {
        beforePropertyWrite("endingDate", this.endingDate, endingDate);
        this.endingDate = endingDate;
    }

    public LocalDateTime getEndingDate() {
        beforePropertyRead("endingDate");
        return this.endingDate;
    }

    public void setId(BigDecimal id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public BigDecimal getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setInsertDate(LocalDateTime insertDate) {
        beforePropertyWrite("insertDate", this.insertDate, insertDate);
        this.insertDate = insertDate;
    }

    public LocalDateTime getInsertDate() {
        beforePropertyRead("insertDate");
        return this.insertDate;
    }

    public void setLastUpdate(LocalDateTime lastUpdate) {
        beforePropertyWrite("lastUpdate", this.lastUpdate, lastUpdate);
        this.lastUpdate = lastUpdate;
    }

    public LocalDateTime getLastUpdate() {
        beforePropertyRead("lastUpdate");
        return this.lastUpdate;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setNokReason(String nokReason) {
        beforePropertyWrite("nokReason", this.nokReason, nokReason);
        this.nokReason = nokReason;
    }

    public String getNokReason() {
        beforePropertyRead("nokReason");
        return this.nokReason;
    }

    public void setRef(String ref) {
        beforePropertyWrite("ref", this.ref, ref);
        this.ref = ref;
    }

    public String getRef() {
        beforePropertyRead("ref");
        return this.ref;
    }

    public void setRefParent(String refParent) {
        beforePropertyWrite("refParent", this.refParent, refParent);
        this.refParent = refParent;
    }

    public String getRefParent() {
        beforePropertyRead("refParent");
        return this.refParent;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        beforePropertyWrite("updateDate", this.updateDate, updateDate);
        this.updateDate = updateDate;
    }

    public LocalDateTime getUpdateDate() {
        beforePropertyRead("updateDate");
        return this.updateDate;
    }

    public void setValidated(BigDecimal validated) {
        beforePropertyWrite("validated", this.validated, validated);
        this.validated = validated;
    }

    public BigDecimal getValidated() {
        beforePropertyRead("validated");
        return this.validated;
    }

    public void addToAgencyPtfs(AgencyPtf obj) {
        addToManyTarget("agencyPtfs", obj, true);
    }

    public void removeFromAgencyPtfs(AgencyPtf obj) {
        removeToManyTarget("agencyPtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AgencyPtf> getAgencyPtfs() {
        return (List<AgencyPtf>)readProperty("agencyPtfs");
    }

    public void setBackupTelecom(Telecom backupTelecom) {
        setToOneTarget("backupTelecom", backupTelecom, true);
    }

    public Telecom getBackupTelecom() {
        return (Telecom)readProperty("backupTelecom");
    }

    public void setBackupTrackingSystem(LocSystem backupTrackingSystem) {
        setToOneTarget("backupTrackingSystem", backupTrackingSystem, true);
    }

    public LocSystem getBackupTrackingSystem() {
        return (LocSystem)readProperty("backupTrackingSystem");
    }

    public void addToContactPtfRoles(ContactPtfRole obj) {
        addToManyTarget("contactPtfRoles", obj, true);
    }

    public void removeFromContactPtfRoles(ContactPtfRole obj) {
        removeToManyTarget("contactPtfRoles", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ContactPtfRole> getContactPtfRoles() {
        return (List<ContactPtfRole>)readProperty("contactPtfRoles");
    }

    public void setDataStatus(DataStatus dataStatus) {
        setToOneTarget("dataStatus", dataStatus, true);
    }

    public DataStatus getDataStatus() {
        return (DataStatus)readProperty("dataStatus");
    }

    public void setDoc(Doc doc) {
        setToOneTarget("doc", doc, true);
    }

    public Doc getDoc() {
        return (Doc)readProperty("doc");
    }

    public void addToDocs(Doc obj) {
        addToManyTarget("docs", obj, true);
    }

    public void removeFromDocs(Doc obj) {
        removeToManyTarget("docs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Doc> getDocs() {
        return (List<Doc>)readProperty("docs");
    }

    public void setEndingCause(EndingCause endingCause) {
        setToOneTarget("endingCause", endingCause, true);
    }

    public EndingCause getEndingCause() {
        return (EndingCause)readProperty("endingCause");
    }

    public void addToGliderThemePtfs(GliderThemePtf obj) {
        addToManyTarget("gliderThemePtfs", obj, true);
    }

    public void removeFromGliderThemePtfs(GliderThemePtf obj) {
        removeToManyTarget("gliderThemePtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<GliderThemePtf> getGliderThemePtfs() {
        return (List<GliderThemePtf>)readProperty("gliderThemePtfs");
    }

    public void setLatestObs(ObsLatest latestObs) {
        setToOneTarget("latestObs", latestObs, true);
    }

    public ObsLatest getLatestObs() {
        return (ObsLatest)readProperty("latestObs");
    }

    public void addToLines(Line obj) {
        addToManyTarget("lines", obj, true);
    }

    public void removeFromLines(Line obj) {
        removeToManyTarget("lines", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Line> getLines() {
        return (List<Line>)readProperty("lines");
    }

    public void addToMzmsPtfCountries(MzmsPtfCountry obj) {
        addToManyTarget("mzmsPtfCountries", obj, true);
    }

    public void removeFromMzmsPtfCountries(MzmsPtfCountry obj) {
        removeToManyTarget("mzmsPtfCountries", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<MzmsPtfCountry> getMzmsPtfCountries() {
        return (List<MzmsPtfCountry>)readProperty("mzmsPtfCountries");
    }

    public void addToNcNotifications(NcNotification obj) {
        addToManyTarget("ncNotifications", obj, true);
    }

    public void removeFromNcNotifications(NcNotification obj) {
        removeToManyTarget("ncNotifications", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<NcNotification> getNcNotifications() {
        return (List<NcNotification>)readProperty("ncNotifications");
    }

    public void addToNcSubscriptions(NcSubscription obj) {
        addToManyTarget("ncSubscriptions", obj, true);
    }

    public void removeFromNcSubscriptions(NcSubscription obj) {
        removeToManyTarget("ncSubscriptions", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<NcSubscription> getNcSubscriptions() {
        return (List<NcSubscription>)readProperty("ncSubscriptions");
    }

    public void addToNetworkPtfs(NetworkPtf obj) {
        addToManyTarget("networkPtfs", obj, true);
    }

    public void removeFromNetworkPtfs(NetworkPtf obj) {
        removeToManyTarget("networkPtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<NetworkPtf> getNetworkPtfs() {
        return (List<NetworkPtf>)readProperty("networkPtfs");
    }

    public void addToObsArgoGdacs(ObsArgoGdac obj) {
        addToManyTarget("obsArgoGdacs", obj, true);
    }

    public void removeFromObsArgoGdacs(ObsArgoGdac obj) {
        removeToManyTarget("obsArgoGdacs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ObsArgoGdac> getObsArgoGdacs() {
        return (List<ObsArgoGdac>)readProperty("obsArgoGdacs");
    }

    public void addToObsGlidersGtsOsmcs(ObsGlidersGtsOsmc obj) {
        addToManyTarget("obsGlidersGtsOsmcs", obj, true);
    }

    public void removeFromObsGlidersGtsOsmcs(ObsGlidersGtsOsmc obj) {
        removeToManyTarget("obsGlidersGtsOsmcs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ObsGlidersGtsOsmc> getObsGlidersGtsOsmcs() {
        return (List<ObsGlidersGtsOsmc>)readProperty("obsGlidersGtsOsmcs");
    }

    public void addToObsTsunaGtsOsmcs(ObsTsunaGtsOsmc obj) {
        addToManyTarget("obsTsunaGtsOsmcs", obj, true);
    }

    public void removeFromObsTsunaGtsOsmcs(ObsTsunaGtsOsmc obj) {
        removeToManyTarget("obsTsunaGtsOsmcs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ObsTsunaGtsOsmc> getObsTsunaGtsOsmcs() {
        return (List<ObsTsunaGtsOsmc>)readProperty("obsTsunaGtsOsmcs");
    }

    public void addToObss(Obs obj) {
        addToManyTarget("obss", obj, true);
    }

    public void removeFromObss(Obs obj) {
        removeToManyTarget("obss", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Obs> getObss() {
        return (List<Obs>)readProperty("obss");
    }

    public void setProgram(Program program) {
        setToOneTarget("program", program, true);
    }

    public Program getProgram() {
        return (Program)readProperty("program");
    }

    public void setPtfAutomation(PtfAutomation ptfAutomation) {
        setToOneTarget("ptfAutomation", ptfAutomation, true);
    }

    public PtfAutomation getPtfAutomation() {
        return (PtfAutomation)readProperty("ptfAutomation");
    }

    public void addToPtfCategories(PtfCategory obj) {
        addToManyTarget("ptfCategories", obj, true);
    }

    public void removeFromPtfCategories(PtfCategory obj) {
        removeToManyTarget("ptfCategories", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfCategory> getPtfCategories() {
        return (List<PtfCategory>)readProperty("ptfCategories");
    }

    public void addToPtfConfigs(PtfConfig obj) {
        addToManyTarget("ptfConfigs", obj, true);
    }

    public void removeFromPtfConfigs(PtfConfig obj) {
        removeToManyTarget("ptfConfigs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfConfig> getPtfConfigs() {
        return (List<PtfConfig>)readProperty("ptfConfigs");
    }

    public void addToPtfCruises(PtfCruise obj) {
        addToManyTarget("ptfCruises", obj, true);
    }

    public void removeFromPtfCruises(PtfCruise obj) {
        removeToManyTarget("ptfCruises", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfCruise> getPtfCruises() {
        return (List<PtfCruise>)readProperty("ptfCruises");
    }

    public void setPtfDepl(PtfDeployment ptfDepl) {
        setToOneTarget("ptfDepl", ptfDepl, true);
    }

    public PtfDeployment getPtfDepl() {
        return (PtfDeployment)readProperty("ptfDepl");
    }

    public void setPtfHardware(PtfHardware ptfHardware) {
        setToOneTarget("ptfHardware", ptfHardware, true);
    }

    public PtfHardware getPtfHardware() {
        return (PtfHardware)readProperty("ptfHardware");
    }

    public void setPtfIdentifiers(PtfIdentifiers ptfIdentifiers) {
        setToOneTarget("ptfIdentifiers", ptfIdentifiers, true);
    }

    public PtfIdentifiers getPtfIdentifiers() {
        return (PtfIdentifiers)readProperty("ptfIdentifiers");
    }

    public void setPtfInspection(PtfInspection ptfInspection) {
        setToOneTarget("ptfInspection", ptfInspection, true);
    }

    public PtfInspection getPtfInspection() {
        return (PtfInspection)readProperty("ptfInspection");
    }

    public void addToPtfLocStatuses(PtfLocStatus obj) {
        addToManyTarget("ptfLocStatuses", obj, true);
    }

    public void removeFromPtfLocStatuses(PtfLocStatus obj) {
        removeToManyTarget("ptfLocStatuses", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfLocStatus> getPtfLocStatuses() {
        return (List<PtfLocStatus>)readProperty("ptfLocStatuses");
    }

    public void addToPtfLocs(PtfLoc obj) {
        addToManyTarget("ptfLocs", obj, true);
    }

    public void removeFromPtfLocs(PtfLoc obj) {
        removeToManyTarget("ptfLocs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfLoc> getPtfLocs() {
        return (List<PtfLoc>)readProperty("ptfLocs");
    }

    public void setPtfModel(PtfModel ptfModel) {
        setToOneTarget("ptfModel", ptfModel, true);
    }

    public PtfModel getPtfModel() {
        return (PtfModel)readProperty("ptfModel");
    }

    public void addToPtfPtfStatuses(PtfPtfStatus obj) {
        addToManyTarget("ptfPtfStatuses", obj, true);
    }

    public void removeFromPtfPtfStatuses(PtfPtfStatus obj) {
        removeToManyTarget("ptfPtfStatuses", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfPtfStatus> getPtfPtfStatuses() {
        return (List<PtfPtfStatus>)readProperty("ptfPtfStatuses");
    }

    public void setPtfSoftware(PtfSoftware ptfSoftware) {
        setToOneTarget("ptfSoftware", ptfSoftware, true);
    }

    public PtfSoftware getPtfSoftware() {
        return (PtfSoftware)readProperty("ptfSoftware");
    }

    public void setPtfStatistics(PtfStatistics ptfStatistics) {
        setToOneTarget("ptfStatistics", ptfStatistics, true);
    }

    public PtfStatistics getPtfStatistics() {
        return (PtfStatistics)readProperty("ptfStatistics");
    }

    public void setPtfStatus(PtfStatus ptfStatus) {
        setToOneTarget("ptfStatus", ptfStatus, true);
    }

    public PtfStatus getPtfStatus() {
        return (PtfStatus)readProperty("ptfStatus");
    }

    public void addToPtfVariableSubs(PtfVariableSub obj) {
        addToManyTarget("ptfVariableSubs", obj, true);
    }

    public void removeFromPtfVariableSubs(PtfVariableSub obj) {
        removeToManyTarget("ptfVariableSubs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfVariableSub> getPtfVariableSubs() {
        return (List<PtfVariableSub>)readProperty("ptfVariableSubs");
    }

    public void addToPtfVariables(PtfVariable obj) {
        addToManyTarget("ptfVariables", obj, true);
    }

    public void removeFromPtfVariables(PtfVariable obj) {
        removeToManyTarget("ptfVariables", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PtfVariable> getPtfVariables() {
        return (List<PtfVariable>)readProperty("ptfVariables");
    }

    public void addToQcFeedbacks(QcFeedback obj) {
        addToManyTarget("qcFeedbacks", obj, true);
    }

    public void removeFromQcFeedbacks(QcFeedback obj) {
        removeToManyTarget("qcFeedbacks", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<QcFeedback> getQcFeedbacks() {
        return (List<QcFeedback>)readProperty("qcFeedbacks");
    }

    public void setRetrieval(Retrieval retrieval) {
        setToOneTarget("retrieval", retrieval, true);
    }

    public Retrieval getRetrieval() {
        return (Retrieval)readProperty("retrieval");
    }

    public void addToServices(Service obj) {
        addToManyTarget("services", obj, true);
    }

    public void removeFromServices(Service obj) {
        removeToManyTarget("services", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Service> getServices() {
        return (List<Service>)readProperty("services");
    }

    public void addToSitePtfs(SitePtf obj) {
        addToManyTarget("sitePtfs", obj, true);
    }

    public void removeFromSitePtfs(SitePtf obj) {
        removeToManyTarget("sitePtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<SitePtf> getSitePtfs() {
        return (List<SitePtf>)readProperty("sitePtfs");
    }

    public void setTelecom(Telecom telecom) {
        setToOneTarget("telecom", telecom, true);
    }

    public Telecom getTelecom() {
        return (Telecom)readProperty("telecom");
    }

    public void setTrackingSystem(LocSystem trackingSystem) {
        setToOneTarget("trackingSystem", trackingSystem, true);
    }

    public LocSystem getTrackingSystem() {
        return (LocSystem)readProperty("trackingSystem");
    }

    public void addToWebFrequentations(WebFrequentation obj) {
        addToManyTarget("webFrequentations", obj, true);
    }

    public void removeFromWebFrequentations(WebFrequentation obj) {
        removeToManyTarget("webFrequentations", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<WebFrequentation> getWebFrequentations() {
        return (List<WebFrequentation>)readProperty("webFrequentations");
    }

    public void addToWeblinkPtfs(WeblinkPtf obj) {
        addToManyTarget("weblinkPtfs", obj, true);
    }

    public void removeFromWeblinkPtfs(WeblinkPtf obj) {
        removeToManyTarget("weblinkPtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<WeblinkPtf> getWeblinkPtfs() {
        return (List<WeblinkPtf>)readProperty("weblinkPtfs");
    }

    public void addToWeblinks(Weblink obj) {
        addToManyTarget("weblinks", obj, true);
    }

    public void removeFromWeblinks(Weblink obj) {
        removeToManyTarget("weblinks", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Weblink> getWeblinks() {
        return (List<Weblink>)readProperty("weblinks");
    }

    public void addToWmos(Wmo obj) {
        addToManyTarget("wmos", obj, true);
    }

    public void removeFromWmos(Wmo obj) {
        removeToManyTarget("wmos", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Wmo> getWmos() {
        return (List<Wmo>)readProperty("wmos");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "activityCriterion":
                return this.activityCriterion;
            case "age":
                return this.age;
            case "ageWeight":
                return this.ageWeight;
            case "closureCriterion":
                return this.closureCriterion;
            case "dataUrl":
                return this.dataUrl;
            case "deleteTag":
                return this.deleteTag;
            case "description":
                return this.description;
            case "eNotificationDate":
                return this.eNotificationDate;
            case "endingDate":
                return this.endingDate;
            case "id":
                return this.id;
            case "insertDate":
                return this.insertDate;
            case "lastUpdate":
                return this.lastUpdate;
            case "name":
                return this.name;
            case "nokReason":
                return this.nokReason;
            case "ref":
                return this.ref;
            case "refParent":
                return this.refParent;
            case "updateDate":
                return this.updateDate;
            case "validated":
                return this.validated;
            case "agencyPtfs":
                return this.agencyPtfs;
            case "backupTelecom":
                return this.backupTelecom;
            case "backupTrackingSystem":
                return this.backupTrackingSystem;
            case "contactPtfRoles":
                return this.contactPtfRoles;
            case "dataStatus":
                return this.dataStatus;
            case "doc":
                return this.doc;
            case "docs":
                return this.docs;
            case "endingCause":
                return this.endingCause;
            case "gliderThemePtfs":
                return this.gliderThemePtfs;
            case "latestObs":
                return this.latestObs;
            case "lines":
                return this.lines;
            case "mzmsPtfCountries":
                return this.mzmsPtfCountries;
            case "ncNotifications":
                return this.ncNotifications;
            case "ncSubscriptions":
                return this.ncSubscriptions;
            case "networkPtfs":
                return this.networkPtfs;
            case "obsArgoGdacs":
                return this.obsArgoGdacs;
            case "obsGlidersGtsOsmcs":
                return this.obsGlidersGtsOsmcs;
            case "obsTsunaGtsOsmcs":
                return this.obsTsunaGtsOsmcs;
            case "obss":
                return this.obss;
            case "program":
                return this.program;
            case "ptfAutomation":
                return this.ptfAutomation;
            case "ptfCategories":
                return this.ptfCategories;
            case "ptfConfigs":
                return this.ptfConfigs;
            case "ptfCruises":
                return this.ptfCruises;
            case "ptfDepl":
                return this.ptfDepl;
            case "ptfHardware":
                return this.ptfHardware;
            case "ptfIdentifiers":
                return this.ptfIdentifiers;
            case "ptfInspection":
                return this.ptfInspection;
            case "ptfLocStatuses":
                return this.ptfLocStatuses;
            case "ptfLocs":
                return this.ptfLocs;
            case "ptfModel":
                return this.ptfModel;
            case "ptfPtfStatuses":
                return this.ptfPtfStatuses;
            case "ptfSoftware":
                return this.ptfSoftware;
            case "ptfStatistics":
                return this.ptfStatistics;
            case "ptfStatus":
                return this.ptfStatus;
            case "ptfVariableSubs":
                return this.ptfVariableSubs;
            case "ptfVariables":
                return this.ptfVariables;
            case "qcFeedbacks":
                return this.qcFeedbacks;
            case "retrieval":
                return this.retrieval;
            case "services":
                return this.services;
            case "sitePtfs":
                return this.sitePtfs;
            case "telecom":
                return this.telecom;
            case "trackingSystem":
                return this.trackingSystem;
            case "webFrequentations":
                return this.webFrequentations;
            case "weblinkPtfs":
                return this.weblinkPtfs;
            case "weblinks":
                return this.weblinks;
            case "wmos":
                return this.wmos;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "activityCriterion":
                this.activityCriterion = (BigDecimal)val;
                break;
            case "age":
                this.age = (BigDecimal)val;
                break;
            case "ageWeight":
                this.ageWeight = (BigDecimal)val;
                break;
            case "closureCriterion":
                this.closureCriterion = (BigDecimal)val;
                break;
            case "dataUrl":
                this.dataUrl = (String)val;
                break;
            case "deleteTag":
                this.deleteTag = (BigDecimal)val;
                break;
            case "description":
                this.description = (String)val;
                break;
            case "eNotificationDate":
                this.eNotificationDate = (LocalDateTime)val;
                break;
            case "endingDate":
                this.endingDate = (LocalDateTime)val;
                break;
            case "id":
                this.id = (BigDecimal)val;
                break;
            case "insertDate":
                this.insertDate = (LocalDateTime)val;
                break;
            case "lastUpdate":
                this.lastUpdate = (LocalDateTime)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "nokReason":
                this.nokReason = (String)val;
                break;
            case "ref":
                this.ref = (String)val;
                break;
            case "refParent":
                this.refParent = (String)val;
                break;
            case "updateDate":
                this.updateDate = (LocalDateTime)val;
                break;
            case "validated":
                this.validated = (BigDecimal)val;
                break;
            case "agencyPtfs":
                this.agencyPtfs = val;
                break;
            case "backupTelecom":
                this.backupTelecom = val;
                break;
            case "backupTrackingSystem":
                this.backupTrackingSystem = val;
                break;
            case "contactPtfRoles":
                this.contactPtfRoles = val;
                break;
            case "dataStatus":
                this.dataStatus = val;
                break;
            case "doc":
                this.doc = val;
                break;
            case "docs":
                this.docs = val;
                break;
            case "endingCause":
                this.endingCause = val;
                break;
            case "gliderThemePtfs":
                this.gliderThemePtfs = val;
                break;
            case "latestObs":
                this.latestObs = val;
                break;
            case "lines":
                this.lines = val;
                break;
            case "mzmsPtfCountries":
                this.mzmsPtfCountries = val;
                break;
            case "ncNotifications":
                this.ncNotifications = val;
                break;
            case "ncSubscriptions":
                this.ncSubscriptions = val;
                break;
            case "networkPtfs":
                this.networkPtfs = val;
                break;
            case "obsArgoGdacs":
                this.obsArgoGdacs = val;
                break;
            case "obsGlidersGtsOsmcs":
                this.obsGlidersGtsOsmcs = val;
                break;
            case "obsTsunaGtsOsmcs":
                this.obsTsunaGtsOsmcs = val;
                break;
            case "obss":
                this.obss = val;
                break;
            case "program":
                this.program = val;
                break;
            case "ptfAutomation":
                this.ptfAutomation = val;
                break;
            case "ptfCategories":
                this.ptfCategories = val;
                break;
            case "ptfConfigs":
                this.ptfConfigs = val;
                break;
            case "ptfCruises":
                this.ptfCruises = val;
                break;
            case "ptfDepl":
                this.ptfDepl = val;
                break;
            case "ptfHardware":
                this.ptfHardware = val;
                break;
            case "ptfIdentifiers":
                this.ptfIdentifiers = val;
                break;
            case "ptfInspection":
                this.ptfInspection = val;
                break;
            case "ptfLocStatuses":
                this.ptfLocStatuses = val;
                break;
            case "ptfLocs":
                this.ptfLocs = val;
                break;
            case "ptfModel":
                this.ptfModel = val;
                break;
            case "ptfPtfStatuses":
                this.ptfPtfStatuses = val;
                break;
            case "ptfSoftware":
                this.ptfSoftware = val;
                break;
            case "ptfStatistics":
                this.ptfStatistics = val;
                break;
            case "ptfStatus":
                this.ptfStatus = val;
                break;
            case "ptfVariableSubs":
                this.ptfVariableSubs = val;
                break;
            case "ptfVariables":
                this.ptfVariables = val;
                break;
            case "qcFeedbacks":
                this.qcFeedbacks = val;
                break;
            case "retrieval":
                this.retrieval = val;
                break;
            case "services":
                this.services = val;
                break;
            case "sitePtfs":
                this.sitePtfs = val;
                break;
            case "telecom":
                this.telecom = val;
                break;
            case "trackingSystem":
                this.trackingSystem = val;
                break;
            case "webFrequentations":
                this.webFrequentations = val;
                break;
            case "weblinkPtfs":
                this.weblinkPtfs = val;
                break;
            case "weblinks":
                this.weblinks = val;
                break;
            case "wmos":
                this.wmos = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.activityCriterion);
        out.writeObject(this.age);
        out.writeObject(this.ageWeight);
        out.writeObject(this.closureCriterion);
        out.writeObject(this.dataUrl);
        out.writeObject(this.deleteTag);
        out.writeObject(this.description);
        out.writeObject(this.eNotificationDate);
        out.writeObject(this.endingDate);
        out.writeObject(this.id);
        out.writeObject(this.insertDate);
        out.writeObject(this.lastUpdate);
        out.writeObject(this.name);
        out.writeObject(this.nokReason);
        out.writeObject(this.ref);
        out.writeObject(this.refParent);
        out.writeObject(this.updateDate);
        out.writeObject(this.validated);
        out.writeObject(this.agencyPtfs);
        out.writeObject(this.backupTelecom);
        out.writeObject(this.backupTrackingSystem);
        out.writeObject(this.contactPtfRoles);
        out.writeObject(this.dataStatus);
        out.writeObject(this.doc);
        out.writeObject(this.docs);
        out.writeObject(this.endingCause);
        out.writeObject(this.gliderThemePtfs);
        out.writeObject(this.latestObs);
        out.writeObject(this.lines);
        out.writeObject(this.mzmsPtfCountries);
        out.writeObject(this.ncNotifications);
        out.writeObject(this.ncSubscriptions);
        out.writeObject(this.networkPtfs);
        out.writeObject(this.obsArgoGdacs);
        out.writeObject(this.obsGlidersGtsOsmcs);
        out.writeObject(this.obsTsunaGtsOsmcs);
        out.writeObject(this.obss);
        out.writeObject(this.program);
        out.writeObject(this.ptfAutomation);
        out.writeObject(this.ptfCategories);
        out.writeObject(this.ptfConfigs);
        out.writeObject(this.ptfCruises);
        out.writeObject(this.ptfDepl);
        out.writeObject(this.ptfHardware);
        out.writeObject(this.ptfIdentifiers);
        out.writeObject(this.ptfInspection);
        out.writeObject(this.ptfLocStatuses);
        out.writeObject(this.ptfLocs);
        out.writeObject(this.ptfModel);
        out.writeObject(this.ptfPtfStatuses);
        out.writeObject(this.ptfSoftware);
        out.writeObject(this.ptfStatistics);
        out.writeObject(this.ptfStatus);
        out.writeObject(this.ptfVariableSubs);
        out.writeObject(this.ptfVariables);
        out.writeObject(this.qcFeedbacks);
        out.writeObject(this.retrieval);
        out.writeObject(this.services);
        out.writeObject(this.sitePtfs);
        out.writeObject(this.telecom);
        out.writeObject(this.trackingSystem);
        out.writeObject(this.webFrequentations);
        out.writeObject(this.weblinkPtfs);
        out.writeObject(this.weblinks);
        out.writeObject(this.wmos);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.activityCriterion = (BigDecimal)in.readObject();
        this.age = (BigDecimal)in.readObject();
        this.ageWeight = (BigDecimal)in.readObject();
        this.closureCriterion = (BigDecimal)in.readObject();
        this.dataUrl = (String)in.readObject();
        this.deleteTag = (BigDecimal)in.readObject();
        this.description = (String)in.readObject();
        this.eNotificationDate = (LocalDateTime)in.readObject();
        this.endingDate = (LocalDateTime)in.readObject();
        this.id = (BigDecimal)in.readObject();
        this.insertDate = (LocalDateTime)in.readObject();
        this.lastUpdate = (LocalDateTime)in.readObject();
        this.name = (String)in.readObject();
        this.nokReason = (String)in.readObject();
        this.ref = (String)in.readObject();
        this.refParent = (String)in.readObject();
        this.updateDate = (LocalDateTime)in.readObject();
        this.validated = (BigDecimal)in.readObject();
        this.agencyPtfs = in.readObject();
        this.backupTelecom = in.readObject();
        this.backupTrackingSystem = in.readObject();
        this.contactPtfRoles = in.readObject();
        this.dataStatus = in.readObject();
        this.doc = in.readObject();
        this.docs = in.readObject();
        this.endingCause = in.readObject();
        this.gliderThemePtfs = in.readObject();
        this.latestObs = in.readObject();
        this.lines = in.readObject();
        this.mzmsPtfCountries = in.readObject();
        this.ncNotifications = in.readObject();
        this.ncSubscriptions = in.readObject();
        this.networkPtfs = in.readObject();
        this.obsArgoGdacs = in.readObject();
        this.obsGlidersGtsOsmcs = in.readObject();
        this.obsTsunaGtsOsmcs = in.readObject();
        this.obss = in.readObject();
        this.program = in.readObject();
        this.ptfAutomation = in.readObject();
        this.ptfCategories = in.readObject();
        this.ptfConfigs = in.readObject();
        this.ptfCruises = in.readObject();
        this.ptfDepl = in.readObject();
        this.ptfHardware = in.readObject();
        this.ptfIdentifiers = in.readObject();
        this.ptfInspection = in.readObject();
        this.ptfLocStatuses = in.readObject();
        this.ptfLocs = in.readObject();
        this.ptfModel = in.readObject();
        this.ptfPtfStatuses = in.readObject();
        this.ptfSoftware = in.readObject();
        this.ptfStatistics = in.readObject();
        this.ptfStatus = in.readObject();
        this.ptfVariableSubs = in.readObject();
        this.ptfVariables = in.readObject();
        this.qcFeedbacks = in.readObject();
        this.retrieval = in.readObject();
        this.services = in.readObject();
        this.sitePtfs = in.readObject();
        this.telecom = in.readObject();
        this.trackingSystem = in.readObject();
        this.webFrequentations = in.readObject();
        this.weblinkPtfs = in.readObject();
        this.weblinks = in.readObject();
        this.wmos = in.readObject();
    }

}
