package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.oceanops.api.orm.QcFeedback;
import org.oceanops.api.orm.Variable;

/**
 * Class _QcFeedbackVariable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _QcFeedbackVariable extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String QC_FEEDBACK_ID_PK_COLUMN = "QC_FEEDBACK_ID";
    public static final String VARIABLE_ID_PK_COLUMN = "VARIABLE_ID";

    public static final NumericProperty<Integer> QC_FEEDBACK_ID = PropertyFactory.createNumeric("qcFeedbackId", Integer.class);
    public static final NumericProperty<Integer> VARIABLE_ID = PropertyFactory.createNumeric("variableId", Integer.class);
    public static final EntityProperty<QcFeedback> QC_FEEDBACK = PropertyFactory.createEntity("qcFeedback", QcFeedback.class);
    public static final EntityProperty<Variable> VARIABLE = PropertyFactory.createEntity("variable", Variable.class);

    protected Integer qcFeedbackId;
    protected Integer variableId;

    protected Object qcFeedback;
    protected Object variable;

    public void setQcFeedbackId(Integer qcFeedbackId) {
        beforePropertyWrite("qcFeedbackId", this.qcFeedbackId, qcFeedbackId);
        this.qcFeedbackId = qcFeedbackId;
    }

    public Integer getQcFeedbackId() {
        beforePropertyRead("qcFeedbackId");
        return this.qcFeedbackId;
    }

    public void setVariableId(Integer variableId) {
        beforePropertyWrite("variableId", this.variableId, variableId);
        this.variableId = variableId;
    }

    public Integer getVariableId() {
        beforePropertyRead("variableId");
        return this.variableId;
    }

    public void setQcFeedback(QcFeedback qcFeedback) {
        setToOneTarget("qcFeedback", qcFeedback, true);
    }

    public QcFeedback getQcFeedback() {
        return (QcFeedback)readProperty("qcFeedback");
    }

    public void setVariable(Variable variable) {
        setToOneTarget("variable", variable, true);
    }

    public Variable getVariable() {
        return (Variable)readProperty("variable");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "qcFeedbackId":
                return this.qcFeedbackId;
            case "variableId":
                return this.variableId;
            case "qcFeedback":
                return this.qcFeedback;
            case "variable":
                return this.variable;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "qcFeedbackId":
                this.qcFeedbackId = (Integer)val;
                break;
            case "variableId":
                this.variableId = (Integer)val;
                break;
            case "qcFeedback":
                this.qcFeedback = val;
                break;
            case "variable":
                this.variable = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.qcFeedbackId);
        out.writeObject(this.variableId);
        out.writeObject(this.qcFeedback);
        out.writeObject(this.variable);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.qcFeedbackId = (Integer)in.readObject();
        this.variableId = (Integer)in.readObject();
        this.qcFeedback = in.readObject();
        this.variable = in.readObject();
    }

}
