package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.oceanops.api.orm.Ptf;
import org.oceanops.api.orm.Weblink;

/**
 * Class _WeblinkPtf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WeblinkPtf extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String PTF_ID_PK_COLUMN = "PTF_ID";
    public static final String WEBLINK_ID_PK_COLUMN = "WEBLINK_ID";

    public static final NumericProperty<Integer> PTF_ID = PropertyFactory.createNumeric("ptfId", Integer.class);
    public static final NumericProperty<Integer> WEBLINK_ID = PropertyFactory.createNumeric("weblinkId", Integer.class);
    public static final EntityProperty<Ptf> PTF = PropertyFactory.createEntity("ptf", Ptf.class);
    public static final EntityProperty<Weblink> WEBLINK = PropertyFactory.createEntity("weblink", Weblink.class);

    protected Integer ptfId;
    protected Integer weblinkId;

    protected Object ptf;
    protected Object weblink;

    public void setPtfId(Integer ptfId) {
        beforePropertyWrite("ptfId", this.ptfId, ptfId);
        this.ptfId = ptfId;
    }

    public Integer getPtfId() {
        beforePropertyRead("ptfId");
        return this.ptfId;
    }

    public void setWeblinkId(Integer weblinkId) {
        beforePropertyWrite("weblinkId", this.weblinkId, weblinkId);
        this.weblinkId = weblinkId;
    }

    public Integer getWeblinkId() {
        beforePropertyRead("weblinkId");
        return this.weblinkId;
    }

    public void setPtf(Ptf ptf) {
        setToOneTarget("ptf", ptf, true);
    }

    public Ptf getPtf() {
        return (Ptf)readProperty("ptf");
    }

    public void setWeblink(Weblink weblink) {
        setToOneTarget("weblink", weblink, true);
    }

    public Weblink getWeblink() {
        return (Weblink)readProperty("weblink");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "ptfId":
                return this.ptfId;
            case "weblinkId":
                return this.weblinkId;
            case "ptf":
                return this.ptf;
            case "weblink":
                return this.weblink;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "ptfId":
                this.ptfId = (Integer)val;
                break;
            case "weblinkId":
                this.weblinkId = (Integer)val;
                break;
            case "ptf":
                this.ptf = val;
                break;
            case "weblink":
                this.weblink = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.ptfId);
        out.writeObject(this.weblinkId);
        out.writeObject(this.ptf);
        out.writeObject(this.weblink);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.ptfId = (Integer)in.readObject();
        this.weblinkId = (Integer)in.readObject();
        this.ptf = in.readObject();
        this.weblink = in.readObject();
    }

}
