package org.oceanops.api.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.DateProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.api.orm.Ptf;

/**
 * Class _Wmo was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Wmo extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final DateProperty<LocalDateTime> END_DATE = PropertyFactory.createDate("endDate", LocalDateTime.class);
    public static final NumericProperty<BigDecimal> FIVEDIGIT_DUPL_EXISTS = PropertyFactory.createNumeric("fivedigitDuplExists", BigDecimal.class);
    public static final NumericProperty<BigDecimal> ID = PropertyFactory.createNumeric("id", BigDecimal.class);
    public static final NumericProperty<BigDecimal> MASK = PropertyFactory.createNumeric("mask", BigDecimal.class);
    public static final DateProperty<LocalDateTime> START_DATE = PropertyFactory.createDate("startDate", LocalDateTime.class);
    public static final StringProperty<String> WMO = PropertyFactory.createString("wmo", String.class);
    public static final EntityProperty<Ptf> PTF = PropertyFactory.createEntity("ptf", Ptf.class);

    protected LocalDateTime endDate;
    protected BigDecimal fivedigitDuplExists;
    protected BigDecimal id;
    protected BigDecimal mask;
    protected LocalDateTime startDate;
    protected String wmo;

    protected Object ptf;

    public void setEndDate(LocalDateTime endDate) {
        beforePropertyWrite("endDate", this.endDate, endDate);
        this.endDate = endDate;
    }

    public LocalDateTime getEndDate() {
        beforePropertyRead("endDate");
        return this.endDate;
    }

    public void setFivedigitDuplExists(BigDecimal fivedigitDuplExists) {
        beforePropertyWrite("fivedigitDuplExists", this.fivedigitDuplExists, fivedigitDuplExists);
        this.fivedigitDuplExists = fivedigitDuplExists;
    }

    public BigDecimal getFivedigitDuplExists() {
        beforePropertyRead("fivedigitDuplExists");
        return this.fivedigitDuplExists;
    }

    public void setId(BigDecimal id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public BigDecimal getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setMask(BigDecimal mask) {
        beforePropertyWrite("mask", this.mask, mask);
        this.mask = mask;
    }

    public BigDecimal getMask() {
        beforePropertyRead("mask");
        return this.mask;
    }

    public void setStartDate(LocalDateTime startDate) {
        beforePropertyWrite("startDate", this.startDate, startDate);
        this.startDate = startDate;
    }

    public LocalDateTime getStartDate() {
        beforePropertyRead("startDate");
        return this.startDate;
    }

    public void setWmo(String wmo) {
        beforePropertyWrite("wmo", this.wmo, wmo);
        this.wmo = wmo;
    }

    public String getWmo() {
        beforePropertyRead("wmo");
        return this.wmo;
    }

    public void setPtf(Ptf ptf) {
        setToOneTarget("ptf", ptf, true);
    }

    public Ptf getPtf() {
        return (Ptf)readProperty("ptf");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "endDate":
                return this.endDate;
            case "fivedigitDuplExists":
                return this.fivedigitDuplExists;
            case "id":
                return this.id;
            case "mask":
                return this.mask;
            case "startDate":
                return this.startDate;
            case "wmo":
                return this.wmo;
            case "ptf":
                return this.ptf;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "endDate":
                this.endDate = (LocalDateTime)val;
                break;
            case "fivedigitDuplExists":
                this.fivedigitDuplExists = (BigDecimal)val;
                break;
            case "id":
                this.id = (BigDecimal)val;
                break;
            case "mask":
                this.mask = (BigDecimal)val;
                break;
            case "startDate":
                this.startDate = (LocalDateTime)val;
                break;
            case "wmo":
                this.wmo = (String)val;
                break;
            case "ptf":
                this.ptf = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.endDate);
        out.writeObject(this.fivedigitDuplExists);
        out.writeObject(this.id);
        out.writeObject(this.mask);
        out.writeObject(this.startDate);
        out.writeObject(this.wmo);
        out.writeObject(this.ptf);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.endDate = (LocalDateTime)in.readObject();
        this.fivedigitDuplExists = (BigDecimal)in.readObject();
        this.id = (BigDecimal)in.readObject();
        this.mask = (BigDecimal)in.readObject();
        this.startDate = (LocalDateTime)in.readObject();
        this.wmo = (String)in.readObject();
        this.ptf = in.readObject();
    }

}
