package jcommops.db.orm.rest.auto;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.Agency;
import jcommops.db.orm.rest.DacType;
import jcommops.db.orm.rest.MasterProg;

/**
 * Class _AgencyDacType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AgencyDacType extends CayenneDataObject {

    public static final String DATA_PATH_PROPERTY = "dataPath";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String NAME_SHORT_PROPERTY = "nameShort";
    public static final String OLD_DAC_ID_PROPERTY = "oldDacId";
    public static final String OP_MAIL_PROPERTY = "opMail";
    public static final String TO_AGENCY_PROPERTY = "toAgency";
    public static final String TO_DAC_TYPE_PROPERTY = "toDacType";
    public static final String TO_MASTER_PROG_PROPERTY = "toMasterProg";

    public static final String AGENCY_ID_PK_COLUMN = "AGENCY_ID";
    public static final String DAC_TYPE_ID_PK_COLUMN = "DAC_TYPE_ID";
    public static final String MASTER_PROGRAM_ID_PK_COLUMN = "MASTER_PROGRAM_ID";

    public void setDataPath(String dataPath) {
        writeProperty(DATA_PATH_PROPERTY, dataPath);
    }
    public String getDataPath() {
        return (String)readProperty(DATA_PATH_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNameShort(String nameShort) {
        writeProperty(NAME_SHORT_PROPERTY, nameShort);
    }
    public String getNameShort() {
        return (String)readProperty(NAME_SHORT_PROPERTY);
    }

    public void setOldDacId(Integer oldDacId) {
        writeProperty(OLD_DAC_ID_PROPERTY, oldDacId);
    }
    public Integer getOldDacId() {
        return (Integer)readProperty(OLD_DAC_ID_PROPERTY);
    }

    public void setOpMail(String opMail) {
        writeProperty(OP_MAIL_PROPERTY, opMail);
    }
    public String getOpMail() {
        return (String)readProperty(OP_MAIL_PROPERTY);
    }

    public void setToAgency(Agency toAgency) {
        setToOneTarget(TO_AGENCY_PROPERTY, toAgency, true);
    }

    public Agency getToAgency() {
        return (Agency)readProperty(TO_AGENCY_PROPERTY);
    }


    public void setToDacType(DacType toDacType) {
        setToOneTarget(TO_DAC_TYPE_PROPERTY, toDacType, true);
    }

    public DacType getToDacType() {
        return (DacType)readProperty(TO_DAC_TYPE_PROPERTY);
    }


    public void setToMasterProg(MasterProg toMasterProg) {
        setToOneTarget(TO_MASTER_PROG_PROPERTY, toMasterProg, true);
    }

    public MasterProg getToMasterProg() {
        return (MasterProg)readProperty(TO_MASTER_PROG_PROPERTY);
    }


}
