package jcommops.db.orm.rest.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.AgencyDacType;
import jcommops.db.orm.rest.AgencyPtf;
import jcommops.db.orm.rest.Contact;
import jcommops.db.orm.rest.Country;
import jcommops.db.orm.rest.Cruise;
import jcommops.db.orm.rest.Image;
import jcommops.db.orm.rest.Obs;
import jcommops.db.orm.rest.ProgramAgency;
import jcommops.db.orm.rest.PtfFirmware;
import jcommops.db.orm.rest.PtfHullType;
import jcommops.db.orm.rest.PtfModel;
import jcommops.db.orm.rest.QcFeedback;
import jcommops.db.orm.rest.SensorModel;
import jcommops.db.orm.rest.UserGroupAgency;
import jcommops.db.orm.rest.Weblink;

/**
 * Class _Agency was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Agency extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String DEPLOYER_PROPERTY = "deployer";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EMAIL_PROPERTY = "email";
    public static final String FAX_PROPERTY = "fax";
    public static final String MANUF_PROPERTY = "manuf";
    public static final String NAME_PROPERTY = "name";
    public static final String NAME_SHORT_PROPERTY = "nameShort";
    public static final String PURCHASER_PROPERTY = "purchaser";
    public static final String SHAPE_PROPERTY = "shape";
    public static final String TEL_PROPERTY = "tel";
    public static final String AGENCY_DAC_TYPE_ARRAY_PROPERTY = "agencyDacTypeArray";
    public static final String AGENCY_PTF_ARRAY_PROPERTY = "agencyPtfArray";
    public static final String CONTACT_ARRAY_PROPERTY = "contactArray";
    public static final String CRUISE_ARRAY_PROPERTY = "cruiseArray";
    public static final String OBS_ARRAY_PROPERTY = "obsArray";
    public static final String OBS_ARRAY1_PROPERTY = "obsArray1";
    public static final String PROGRAM_AGENCY_ARRAY_PROPERTY = "programAgencyArray";
    public static final String PTF_FIRMWARE_ARRAY_PROPERTY = "ptfFirmwareArray";
    public static final String PTF_HULL_TYPE_ARRAY_PROPERTY = "ptfHullTypeArray";
    public static final String PTF_MODEL_ARRAY_PROPERTY = "ptfModelArray";
    public static final String QC_FEEDBACK_ARRAY_PROPERTY = "qcFeedbackArray";
    public static final String SENSOR_MODEL_ARRAY_PROPERTY = "sensorModelArray";
    public static final String TO_COUNTRY_PROPERTY = "toCountry";
    public static final String TO_IMAGE_PROPERTY = "toImage";
    public static final String TO_WEBLINK_PROPERTY = "toWeblink";
    public static final String USER_GROUP_AGENCY_ARRAY_PROPERTY = "userGroupAgencyArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setDeployer(Integer deployer) {
        writeProperty(DEPLOYER_PROPERTY, deployer);
    }
    public Integer getDeployer() {
        return (Integer)readProperty(DEPLOYER_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setFax(String fax) {
        writeProperty(FAX_PROPERTY, fax);
    }
    public String getFax() {
        return (String)readProperty(FAX_PROPERTY);
    }

    public void setManuf(Integer manuf) {
        writeProperty(MANUF_PROPERTY, manuf);
    }
    public Integer getManuf() {
        return (Integer)readProperty(MANUF_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setNameShort(String nameShort) {
        writeProperty(NAME_SHORT_PROPERTY, nameShort);
    }
    public String getNameShort() {
        return (String)readProperty(NAME_SHORT_PROPERTY);
    }

    public void setPurchaser(Integer purchaser) {
        writeProperty(PURCHASER_PROPERTY, purchaser);
    }
    public Integer getPurchaser() {
        return (Integer)readProperty(PURCHASER_PROPERTY);
    }

   /** public void setShape($importUtils.formatJavaType(${attr.Type}) shape) {
        writeProperty(SHAPE_PROPERTY, shape);
    }
    public $importUtils.formatJavaType(${attr.Type}) getShape() {
        return ($importUtils.formatJavaType(${attr.Type}))readProperty(SHAPE_PROPERTY);
    }
**/
    public void setTel(String tel) {
        writeProperty(TEL_PROPERTY, tel);
    }
    public String getTel() {
        return (String)readProperty(TEL_PROPERTY);
    }

    public void addToAgencyDacTypeArray(AgencyDacType obj) {
        addToManyTarget(AGENCY_DAC_TYPE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromAgencyDacTypeArray(AgencyDacType obj) {
        removeToManyTarget(AGENCY_DAC_TYPE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AgencyDacType> getAgencyDacTypeArray() {
        return (List<AgencyDacType>)readProperty(AGENCY_DAC_TYPE_ARRAY_PROPERTY);
    }


    public void addToAgencyPtfArray(AgencyPtf obj) {
        addToManyTarget(AGENCY_PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromAgencyPtfArray(AgencyPtf obj) {
        removeToManyTarget(AGENCY_PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AgencyPtf> getAgencyPtfArray() {
        return (List<AgencyPtf>)readProperty(AGENCY_PTF_ARRAY_PROPERTY);
    }


    public void addToContactArray(Contact obj) {
        addToManyTarget(CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromContactArray(Contact obj) {
        removeToManyTarget(CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Contact> getContactArray() {
        return (List<Contact>)readProperty(CONTACT_ARRAY_PROPERTY);
    }


    public void addToCruiseArray(Cruise obj) {
        addToManyTarget(CRUISE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromCruiseArray(Cruise obj) {
        removeToManyTarget(CRUISE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Cruise> getCruiseArray() {
        return (List<Cruise>)readProperty(CRUISE_ARRAY_PROPERTY);
    }


    public void addToObsArray(Obs obj) {
        addToManyTarget(OBS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromObsArray(Obs obj) {
        removeToManyTarget(OBS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Obs> getObsArray() {
        return (List<Obs>)readProperty(OBS_ARRAY_PROPERTY);
    }


    public void addToObsArray1(Obs obj) {
        addToManyTarget(OBS_ARRAY1_PROPERTY, obj, true);
    }
    public void removeFromObsArray1(Obs obj) {
        removeToManyTarget(OBS_ARRAY1_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Obs> getObsArray1() {
        return (List<Obs>)readProperty(OBS_ARRAY1_PROPERTY);
    }


    public void addToProgramAgencyArray(ProgramAgency obj) {
        addToManyTarget(PROGRAM_AGENCY_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromProgramAgencyArray(ProgramAgency obj) {
        removeToManyTarget(PROGRAM_AGENCY_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProgramAgency> getProgramAgencyArray() {
        return (List<ProgramAgency>)readProperty(PROGRAM_AGENCY_ARRAY_PROPERTY);
    }


    public void addToPtfFirmwareArray(PtfFirmware obj) {
        addToManyTarget(PTF_FIRMWARE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfFirmwareArray(PtfFirmware obj) {
        removeToManyTarget(PTF_FIRMWARE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfFirmware> getPtfFirmwareArray() {
        return (List<PtfFirmware>)readProperty(PTF_FIRMWARE_ARRAY_PROPERTY);
    }


    public void addToPtfHullTypeArray(PtfHullType obj) {
        addToManyTarget(PTF_HULL_TYPE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfHullTypeArray(PtfHullType obj) {
        removeToManyTarget(PTF_HULL_TYPE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfHullType> getPtfHullTypeArray() {
        return (List<PtfHullType>)readProperty(PTF_HULL_TYPE_ARRAY_PROPERTY);
    }


    public void addToPtfModelArray(PtfModel obj) {
        addToManyTarget(PTF_MODEL_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfModelArray(PtfModel obj) {
        removeToManyTarget(PTF_MODEL_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfModel> getPtfModelArray() {
        return (List<PtfModel>)readProperty(PTF_MODEL_ARRAY_PROPERTY);
    }


    public void addToQcFeedbackArray(QcFeedback obj) {
        addToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromQcFeedbackArray(QcFeedback obj) {
        removeToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<QcFeedback> getQcFeedbackArray() {
        return (List<QcFeedback>)readProperty(QC_FEEDBACK_ARRAY_PROPERTY);
    }


    public void addToSensorModelArray(SensorModel obj) {
        addToManyTarget(SENSOR_MODEL_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSensorModelArray(SensorModel obj) {
        removeToManyTarget(SENSOR_MODEL_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SensorModel> getSensorModelArray() {
        return (List<SensorModel>)readProperty(SENSOR_MODEL_ARRAY_PROPERTY);
    }


    public void setToCountry(Country toCountry) {
        setToOneTarget(TO_COUNTRY_PROPERTY, toCountry, true);
    }

    public Country getToCountry() {
        return (Country)readProperty(TO_COUNTRY_PROPERTY);
    }


    public void setToImage(Image toImage) {
        setToOneTarget(TO_IMAGE_PROPERTY, toImage, true);
    }

    public Image getToImage() {
        return (Image)readProperty(TO_IMAGE_PROPERTY);
    }


    public void setToWeblink(Weblink toWeblink) {
        setToOneTarget(TO_WEBLINK_PROPERTY, toWeblink, true);
    }

    public Weblink getToWeblink() {
        return (Weblink)readProperty(TO_WEBLINK_PROPERTY);
    }


    public void addToUserGroupAgencyArray(UserGroupAgency obj) {
        addToManyTarget(USER_GROUP_AGENCY_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromUserGroupAgencyArray(UserGroupAgency obj) {
        removeToManyTarget(USER_GROUP_AGENCY_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UserGroupAgency> getUserGroupAgencyArray() {
        return (List<UserGroupAgency>)readProperty(USER_GROUP_AGENCY_ARRAY_PROPERTY);
    }


}
