package jcommops.db.orm.rest.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.Agency;
import jcommops.db.orm.rest.Country;
import jcommops.db.orm.rest.CruiseContact;
import jcommops.db.orm.rest.DocContact;
import jcommops.db.orm.rest.Image;
import jcommops.db.orm.rest.MasterProgContact;
import jcommops.db.orm.rest.Meeting;
import jcommops.db.orm.rest.NcNotification;
import jcommops.db.orm.rest.ProgramContact;
import jcommops.db.orm.rest.PtfDeployment;
import jcommops.db.orm.rest.PtfModel;
import jcommops.db.orm.rest.QcFeedback;
import jcommops.db.orm.rest.TelecomFormat;
import jcommops.db.orm.rest.UserGroupContact;
import jcommops.db.orm.rest.WebConnection;
import jcommops.db.orm.rest.WebContactModule;
import jcommops.db.orm.rest.WebQuery;
import jcommops.db.orm.rest.Weblink;

/**
 * Class _Contact was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Contact extends CayenneDataObject {

    public static final String ADDRESS_PROPERTY = "address";
    public static final String ADMIN_PROPERTY = "admin";
    public static final String EMAIL_PROPERTY = "email";
    public static final String EMAIL2_PROPERTY = "email2";
    public static final String FAX_PROPERTY = "fax";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String GREETINGS_PROPERTY = "greetings";
    public static final String IS_PRIVATE_PROPERTY = "isPrivate";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String LAST_UPDATE_PROPERTY = "lastUpdate";
    public static final String LOGIN_PROPERTY = "login";
    public static final String PASSWD_PROPERTY = "passwd";
    public static final String TEL_PROPERTY = "tel";
    public static final String TEL2_PROPERTY = "tel2";
    public static final String TITLE_PROPERTY = "title";
    public static final String CRUISE_CONTACT_ARRAY_PROPERTY = "cruiseContactArray";
    public static final String DOC_CONTACT_ARRAY_PROPERTY = "docContactArray";
    public static final String MASTER_PROG_CONTACT_ARRAY_PROPERTY = "masterProgContactArray";
    public static final String MEETING_ARRAY_PROPERTY = "meetingArray";
    public static final String NC_NOTIFICATION_ARRAY_PROPERTY = "ncNotificationArray";
    public static final String PROGRAM_CONTACT_ARRAY_PROPERTY = "programContactArray";
    public static final String PTF_DEPLOYMENT_ARRAY_PROPERTY = "ptfDeploymentArray";
    public static final String PTF_MODEL_ARRAY_PROPERTY = "ptfModelArray";
    public static final String QC_FEEDBACK_ARRAY_PROPERTY = "qcFeedbackArray";
    public static final String TELECOM_FORMAT_ARRAY_PROPERTY = "telecomFormatArray";
    public static final String TO_AGENCY_PROPERTY = "toAgency";
    public static final String TO_COUNTRY_PROPERTY = "toCountry";
    public static final String TO_IMAGE_PROPERTY = "toImage";
    public static final String TO_WEBLINK_PROPERTY = "toWeblink";
    public static final String USER_GROUP_CONTACT_ARRAY_PROPERTY = "userGroupContactArray";
    public static final String WEB_CONNECTION_ARRAY_PROPERTY = "webConnectionArray";
    public static final String WEB_CONTACT_MODULE_ARRAY_PROPERTY = "webContactModuleArray";
    public static final String WEB_QUERY_ARRAY_PROPERTY = "webQueryArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setAddress(String address) {
        writeProperty(ADDRESS_PROPERTY, address);
    }
    public String getAddress() {
        return (String)readProperty(ADDRESS_PROPERTY);
    }

    public void setAdmin(Integer admin) {
        writeProperty(ADMIN_PROPERTY, admin);
    }
    public Integer getAdmin() {
        return (Integer)readProperty(ADMIN_PROPERTY);
    }

    public void setEmail(String email) {
        writeProperty(EMAIL_PROPERTY, email);
    }
    public String getEmail() {
        return (String)readProperty(EMAIL_PROPERTY);
    }

    public void setEmail2(String email2) {
        writeProperty(EMAIL2_PROPERTY, email2);
    }
    public String getEmail2() {
        return (String)readProperty(EMAIL2_PROPERTY);
    }

    public void setFax(String fax) {
        writeProperty(FAX_PROPERTY, fax);
    }
    public String getFax() {
        return (String)readProperty(FAX_PROPERTY);
    }

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setGreetings(Integer greetings) {
        writeProperty(GREETINGS_PROPERTY, greetings);
    }
    public Integer getGreetings() {
        return (Integer)readProperty(GREETINGS_PROPERTY);
    }

    public void setIsPrivate(Integer isPrivate) {
        writeProperty(IS_PRIVATE_PROPERTY, isPrivate);
    }
    public Integer getIsPrivate() {
        return (Integer)readProperty(IS_PRIVATE_PROPERTY);
    }

    public void setLastName(String lastName) {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName() {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void setLastUpdate(Date lastUpdate) {
        writeProperty(LAST_UPDATE_PROPERTY, lastUpdate);
    }
    public Date getLastUpdate() {
        return (Date)readProperty(LAST_UPDATE_PROPERTY);
    }

    public void setLogin(String login) {
        writeProperty(LOGIN_PROPERTY, login);
    }
    public String getLogin() {
        return (String)readProperty(LOGIN_PROPERTY);
    }

    public void setPasswd(String passwd) {
        writeProperty(PASSWD_PROPERTY, passwd);
    }
    public String getPasswd() {
        return (String)readProperty(PASSWD_PROPERTY);
    }

    public void setTel(String tel) {
        writeProperty(TEL_PROPERTY, tel);
    }
    public String getTel() {
        return (String)readProperty(TEL_PROPERTY);
    }

    public void setTel2(String tel2) {
        writeProperty(TEL2_PROPERTY, tel2);
    }
    public String getTel2() {
        return (String)readProperty(TEL2_PROPERTY);
    }

    public void setTitle(String title) {
        writeProperty(TITLE_PROPERTY, title);
    }
    public String getTitle() {
        return (String)readProperty(TITLE_PROPERTY);
    }

    public void addToCruiseContactArray(CruiseContact obj) {
        addToManyTarget(CRUISE_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromCruiseContactArray(CruiseContact obj) {
        removeToManyTarget(CRUISE_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CruiseContact> getCruiseContactArray() {
        return (List<CruiseContact>)readProperty(CRUISE_CONTACT_ARRAY_PROPERTY);
    }


    public void addToDocContactArray(DocContact obj) {
        addToManyTarget(DOC_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromDocContactArray(DocContact obj) {
        removeToManyTarget(DOC_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DocContact> getDocContactArray() {
        return (List<DocContact>)readProperty(DOC_CONTACT_ARRAY_PROPERTY);
    }


    public void addToMasterProgContactArray(MasterProgContact obj) {
        addToManyTarget(MASTER_PROG_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMasterProgContactArray(MasterProgContact obj) {
        removeToManyTarget(MASTER_PROG_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<MasterProgContact> getMasterProgContactArray() {
        return (List<MasterProgContact>)readProperty(MASTER_PROG_CONTACT_ARRAY_PROPERTY);
    }


    public void addToMeetingArray(Meeting obj) {
        addToManyTarget(MEETING_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromMeetingArray(Meeting obj) {
        removeToManyTarget(MEETING_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Meeting> getMeetingArray() {
        return (List<Meeting>)readProperty(MEETING_ARRAY_PROPERTY);
    }


    public void addToNcNotificationArray(NcNotification obj) {
        addToManyTarget(NC_NOTIFICATION_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromNcNotificationArray(NcNotification obj) {
        removeToManyTarget(NC_NOTIFICATION_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NcNotification> getNcNotificationArray() {
        return (List<NcNotification>)readProperty(NC_NOTIFICATION_ARRAY_PROPERTY);
    }


    public void addToProgramContactArray(ProgramContact obj) {
        addToManyTarget(PROGRAM_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromProgramContactArray(ProgramContact obj) {
        removeToManyTarget(PROGRAM_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ProgramContact> getProgramContactArray() {
        return (List<ProgramContact>)readProperty(PROGRAM_CONTACT_ARRAY_PROPERTY);
    }


    public void addToPtfDeploymentArray(PtfDeployment obj) {
        addToManyTarget(PTF_DEPLOYMENT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfDeploymentArray(PtfDeployment obj) {
        removeToManyTarget(PTF_DEPLOYMENT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfDeployment> getPtfDeploymentArray() {
        return (List<PtfDeployment>)readProperty(PTF_DEPLOYMENT_ARRAY_PROPERTY);
    }


    public void addToPtfModelArray(PtfModel obj) {
        addToManyTarget(PTF_MODEL_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfModelArray(PtfModel obj) {
        removeToManyTarget(PTF_MODEL_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfModel> getPtfModelArray() {
        return (List<PtfModel>)readProperty(PTF_MODEL_ARRAY_PROPERTY);
    }


    public void addToQcFeedbackArray(QcFeedback obj) {
        addToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromQcFeedbackArray(QcFeedback obj) {
        removeToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<QcFeedback> getQcFeedbackArray() {
        return (List<QcFeedback>)readProperty(QC_FEEDBACK_ARRAY_PROPERTY);
    }


    public void addToTelecomFormatArray(TelecomFormat obj) {
        addToManyTarget(TELECOM_FORMAT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromTelecomFormatArray(TelecomFormat obj) {
        removeToManyTarget(TELECOM_FORMAT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TelecomFormat> getTelecomFormatArray() {
        return (List<TelecomFormat>)readProperty(TELECOM_FORMAT_ARRAY_PROPERTY);
    }


    public void setToAgency(Agency toAgency) {
        setToOneTarget(TO_AGENCY_PROPERTY, toAgency, true);
    }

    public Agency getToAgency() {
        return (Agency)readProperty(TO_AGENCY_PROPERTY);
    }


    public void setToCountry(Country toCountry) {
        setToOneTarget(TO_COUNTRY_PROPERTY, toCountry, true);
    }

    public Country getToCountry() {
        return (Country)readProperty(TO_COUNTRY_PROPERTY);
    }


    public void setToImage(Image toImage) {
        setToOneTarget(TO_IMAGE_PROPERTY, toImage, true);
    }

    public Image getToImage() {
        return (Image)readProperty(TO_IMAGE_PROPERTY);
    }


    public void setToWeblink(Weblink toWeblink) {
        setToOneTarget(TO_WEBLINK_PROPERTY, toWeblink, true);
    }

    public Weblink getToWeblink() {
        return (Weblink)readProperty(TO_WEBLINK_PROPERTY);
    }


    public void addToUserGroupContactArray(UserGroupContact obj) {
        addToManyTarget(USER_GROUP_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromUserGroupContactArray(UserGroupContact obj) {
        removeToManyTarget(USER_GROUP_CONTACT_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<UserGroupContact> getUserGroupContactArray() {
        return (List<UserGroupContact>)readProperty(USER_GROUP_CONTACT_ARRAY_PROPERTY);
    }


    public void addToWebConnectionArray(WebConnection obj) {
        addToManyTarget(WEB_CONNECTION_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWebConnectionArray(WebConnection obj) {
        removeToManyTarget(WEB_CONNECTION_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebConnection> getWebConnectionArray() {
        return (List<WebConnection>)readProperty(WEB_CONNECTION_ARRAY_PROPERTY);
    }


    public void addToWebContactModuleArray(WebContactModule obj) {
        addToManyTarget(WEB_CONTACT_MODULE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWebContactModuleArray(WebContactModule obj) {
        removeToManyTarget(WEB_CONTACT_MODULE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebContactModule> getWebContactModuleArray() {
        return (List<WebContactModule>)readProperty(WEB_CONTACT_MODULE_ARRAY_PROPERTY);
    }


    public void addToWebQueryArray(WebQuery obj) {
        addToManyTarget(WEB_QUERY_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWebQueryArray(WebQuery obj) {
        removeToManyTarget(WEB_QUERY_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebQuery> getWebQueryArray() {
        return (List<WebQuery>)readProperty(WEB_QUERY_ARRAY_PROPERTY);
    }


}
