package jcommops.db.orm.rest.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.NcNotification;

/**
 * Class _NcTopic was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _NcTopic extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String IS_PRIVATE_PROPERTY = "isPrivate";
    public static final String NAME_PROPERTY = "name";
    public static final String PARENT_TOPIC_ID_PROPERTY = "parentTopicId";
    public static final String NC_NOTIFICATION_ARRAY_PROPERTY = "ncNotificationArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setIsPrivate(Integer isPrivate) {
        writeProperty(IS_PRIVATE_PROPERTY, isPrivate);
    }
    public Integer getIsPrivate() {
        return (Integer)readProperty(IS_PRIVATE_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setParentTopicId(Integer parentTopicId) {
        writeProperty(PARENT_TOPIC_ID_PROPERTY, parentTopicId);
    }
    public Integer getParentTopicId() {
        return (Integer)readProperty(PARENT_TOPIC_ID_PROPERTY);
    }

    public void addToNcNotificationArray(NcNotification obj) {
        addToManyTarget(NC_NOTIFICATION_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromNcNotificationArray(NcNotification obj) {
        removeToManyTarget(NC_NOTIFICATION_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NcNotification> getNcNotificationArray() {
        return (List<NcNotification>)readProperty(NC_NOTIFICATION_ARRAY_PROPERTY);
    }


}
