package jcommops.db.orm.rest.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.AgencyPtf;
import jcommops.db.orm.rest.DataStatus;
import jcommops.db.orm.rest.Doc;
import jcommops.db.orm.rest.EndingCause;
import jcommops.db.orm.rest.NetworkPtf;
import jcommops.db.orm.rest.Obs;
import jcommops.db.orm.rest.Program;
import jcommops.db.orm.rest.PtfConfig;
import jcommops.db.orm.rest.PtfCruise;
import jcommops.db.orm.rest.PtfDeployment;
import jcommops.db.orm.rest.PtfHardware;
import jcommops.db.orm.rest.PtfIdentifiers;
import jcommops.db.orm.rest.PtfLoc;
import jcommops.db.orm.rest.PtfModel;
import jcommops.db.orm.rest.PtfSensorModel;
import jcommops.db.orm.rest.PtfStatus;
import jcommops.db.orm.rest.PtfVariable;
import jcommops.db.orm.rest.QcFeedback;
import jcommops.db.orm.rest.Retrieval;
import jcommops.db.orm.rest.Site;
import jcommops.db.orm.rest.SitePtf;
import jcommops.db.orm.rest.Telecom;
import jcommops.db.orm.rest.TrackingSystem;
import jcommops.db.orm.rest.Weblink;
import jcommops.db.orm.rest.WeblinkPtf;
import jcommops.db.orm.rest.Wmo;

/**
 * Class _Ptf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Ptf extends CayenneDataObject {

    public static final String ACTIVITY_CRITERION_PROPERTY = "activityCriterion";
    public static final String AGE_PROPERTY = "age";
    public static final String BLACKLISTED_PROPERTY = "blacklisted";
    public static final String CLOSURE_CRITERION_PROPERTY = "closureCriterion";
    public static final String CONFIRM_DATE_PROPERTY = "confirmDate";
    public static final String DELETE_TAG_PROPERTY = "deleteTag";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DROGUE_LOSS_DATE_PROPERTY = "drogueLossDate";
    public static final String E_NOTIFICATION_PROPERTY = "eNotification";
    public static final String E_NOTIFICATION_DATE_PROPERTY = "eNotificationDate";
    public static final String ENDING_DATE_PROPERTY = "endingDate";
    public static final String ICED_OVER_PROPERTY = "icedOver";
    public static final String INSERT_DATE_PROPERTY = "insertDate";
    public static final String LAST_UPDATE_PROPERTY = "lastUpdate";
    public static final String METADATA_AVAILABLE_PROPERTY = "metadataAvailable";
    public static final String NOK_REASON_PROPERTY = "nokReason";
    public static final String REF_PROPERTY = "ref";
    public static final String REF_PARENT_PROPERTY = "refParent";
    public static final String TRACKING_SYSTEM_ID_PROPERTY = "trackingSystemId";
    public static final String UPDATE_DATE_PROPERTY = "updateDate";
    public static final String VALIDATED_PROPERTY = "validated";
    public static final String AGENCY_PTF_ARRAY_PROPERTY = "agencyPtfArray";
    public static final String DOC_ARRAY_PROPERTY = "docArray";
    public static final String NETWORK_PTF_ARRAY_PROPERTY = "networkPtfArray";
    public static final String OBS_ARRAY_PROPERTY = "obsArray";
    public static final String PTF_CONFIG_ARRAY_PROPERTY = "ptfConfigArray";
    public static final String PTF_CRUISE_ARRAY_PROPERTY = "ptfCruiseArray";
    public static final String PTF_LOC_ARRAY_PROPERTY = "ptfLocArray";
    public static final String PTF_SENSOR_MODEL_ARRAY_PROPERTY = "ptfSensorModelArray";
    public static final String PTF_VARIABLE_ARRAY_PROPERTY = "ptfVariableArray";
    public static final String QC_FEEDBACK_ARRAY_PROPERTY = "qcFeedbackArray";
    public static final String SITE_PTF_ARRAY_PROPERTY = "sitePtfArray";
    public static final String TO_DATA_STATUS_PROPERTY = "toDataStatus";
    public static final String TO_ENDING_CAUSE_PROPERTY = "toEndingCause";
    public static final String TO_OBS_PROPERTY = "toObs";
    public static final String TO_PROGRAM_PROPERTY = "toProgram";
    public static final String TO_PTF_DEPLOYMENT_PROPERTY = "toPtfDeployment";
    public static final String TO_PTF_HARDWARE_PROPERTY = "toPtfHardware";
    public static final String TO_PTF_IDENTIFIERS_PROPERTY = "toPtfIdentifiers";
    public static final String TO_PTF_LOC_PROPERTY = "toPtfLoc";
    public static final String TO_PTF_MODEL_PROPERTY = "toPtfModel";
    public static final String TO_PTF_STATUS_PROPERTY = "toPtfStatus";
    public static final String TO_RETRIEVAL_PROPERTY = "toRetrieval";
    public static final String TO_SITE_PROPERTY = "toSite";
    public static final String TO_TELECOM_PROPERTY = "toTelecom";
    public static final String TO_TELECOM1_PROPERTY = "toTelecom1";
    public static final String TO_TRACKING_SYSTEM_PROPERTY = "toTrackingSystem";
    public static final String WEBLINK_ARRAY_PROPERTY = "weblinkArray";
    public static final String WEBLINK_PTF_ARRAY_PROPERTY = "weblinkPtfArray";
    public static final String WMO_ARRAY_PROPERTY = "wmoArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setActivityCriterion(Integer activityCriterion) {
        writeProperty(ACTIVITY_CRITERION_PROPERTY, activityCriterion);
    }
    public Integer getActivityCriterion() {
        return (Integer)readProperty(ACTIVITY_CRITERION_PROPERTY);
    }

    public void setAge(Integer age) {
        writeProperty(AGE_PROPERTY, age);
    }
    public Integer getAge() {
        return (Integer)readProperty(AGE_PROPERTY);
    }

    public void setBlacklisted(Integer blacklisted) {
        writeProperty(BLACKLISTED_PROPERTY, blacklisted);
    }
    public Integer getBlacklisted() {
        return (Integer)readProperty(BLACKLISTED_PROPERTY);
    }

    public void setClosureCriterion(Integer closureCriterion) {
        writeProperty(CLOSURE_CRITERION_PROPERTY, closureCriterion);
    }
    public Integer getClosureCriterion() {
        return (Integer)readProperty(CLOSURE_CRITERION_PROPERTY);
    }

    public void setConfirmDate(Date confirmDate) {
        writeProperty(CONFIRM_DATE_PROPERTY, confirmDate);
    }
    public Date getConfirmDate() {
        return (Date)readProperty(CONFIRM_DATE_PROPERTY);
    }

    public void setDeleteTag(Integer deleteTag) {
        writeProperty(DELETE_TAG_PROPERTY, deleteTag);
    }
    public Integer getDeleteTag() {
        return (Integer)readProperty(DELETE_TAG_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setDrogueLossDate(Date drogueLossDate) {
        writeProperty(DROGUE_LOSS_DATE_PROPERTY, drogueLossDate);
    }
    public Date getDrogueLossDate() {
        return (Date)readProperty(DROGUE_LOSS_DATE_PROPERTY);
    }

    public void setENotification(String eNotification) {
        writeProperty(E_NOTIFICATION_PROPERTY, eNotification);
    }
    public String getENotification() {
        return (String)readProperty(E_NOTIFICATION_PROPERTY);
    }

    public void setENotificationDate(Date eNotificationDate) {
        writeProperty(E_NOTIFICATION_DATE_PROPERTY, eNotificationDate);
    }
    public Date getENotificationDate() {
        return (Date)readProperty(E_NOTIFICATION_DATE_PROPERTY);
    }

    public void setEndingDate(Date endingDate) {
        writeProperty(ENDING_DATE_PROPERTY, endingDate);
    }
    public Date getEndingDate() {
        return (Date)readProperty(ENDING_DATE_PROPERTY);
    }

    public void setIcedOver(Integer icedOver) {
        writeProperty(ICED_OVER_PROPERTY, icedOver);
    }
    public Integer getIcedOver() {
        return (Integer)readProperty(ICED_OVER_PROPERTY);
    }

    public void setInsertDate(Date insertDate) {
        writeProperty(INSERT_DATE_PROPERTY, insertDate);
    }
    public Date getInsertDate() {
        return (Date)readProperty(INSERT_DATE_PROPERTY);
    }

    public void setLastUpdate(Date lastUpdate) {
        writeProperty(LAST_UPDATE_PROPERTY, lastUpdate);
    }
    public Date getLastUpdate() {
        return (Date)readProperty(LAST_UPDATE_PROPERTY);
    }

    public void setMetadataAvailable(Integer metadataAvailable) {
        writeProperty(METADATA_AVAILABLE_PROPERTY, metadataAvailable);
    }
    public Integer getMetadataAvailable() {
        return (Integer)readProperty(METADATA_AVAILABLE_PROPERTY);
    }

    public void setNokReason(String nokReason) {
        writeProperty(NOK_REASON_PROPERTY, nokReason);
    }
    public String getNokReason() {
        return (String)readProperty(NOK_REASON_PROPERTY);
    }

    public void setRef(String ref) {
        writeProperty(REF_PROPERTY, ref);
    }
    public String getRef() {
        return (String)readProperty(REF_PROPERTY);
    }

    public void setRefParent(String refParent) {
        writeProperty(REF_PARENT_PROPERTY, refParent);
    }
    public String getRefParent() {
        return (String)readProperty(REF_PARENT_PROPERTY);
    }

    public void setTrackingSystemId(Integer trackingSystemId) {
        writeProperty(TRACKING_SYSTEM_ID_PROPERTY, trackingSystemId);
    }
    public Integer getTrackingSystemId() {
        return (Integer)readProperty(TRACKING_SYSTEM_ID_PROPERTY);
    }

    public void setUpdateDate(Date updateDate) {
        writeProperty(UPDATE_DATE_PROPERTY, updateDate);
    }
    public Date getUpdateDate() {
        return (Date)readProperty(UPDATE_DATE_PROPERTY);
    }

    public void setValidated(Integer validated) {
        writeProperty(VALIDATED_PROPERTY, validated);
    }
    public Integer getValidated() {
        return (Integer)readProperty(VALIDATED_PROPERTY);
    }

    public void addToAgencyPtfArray(AgencyPtf obj) {
        addToManyTarget(AGENCY_PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromAgencyPtfArray(AgencyPtf obj) {
        removeToManyTarget(AGENCY_PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<AgencyPtf> getAgencyPtfArray() {
        return (List<AgencyPtf>)readProperty(AGENCY_PTF_ARRAY_PROPERTY);
    }


    public void addToDocArray(Doc obj) {
        addToManyTarget(DOC_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromDocArray(Doc obj) {
        removeToManyTarget(DOC_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Doc> getDocArray() {
        return (List<Doc>)readProperty(DOC_ARRAY_PROPERTY);
    }


    public void addToNetworkPtfArray(NetworkPtf obj) {
        addToManyTarget(NETWORK_PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromNetworkPtfArray(NetworkPtf obj) {
        removeToManyTarget(NETWORK_PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<NetworkPtf> getNetworkPtfArray() {
        return (List<NetworkPtf>)readProperty(NETWORK_PTF_ARRAY_PROPERTY);
    }


    public void addToObsArray(Obs obj) {
        addToManyTarget(OBS_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromObsArray(Obs obj) {
        removeToManyTarget(OBS_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Obs> getObsArray() {
        return (List<Obs>)readProperty(OBS_ARRAY_PROPERTY);
    }


    public void addToPtfConfigArray(PtfConfig obj) {
        addToManyTarget(PTF_CONFIG_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfConfigArray(PtfConfig obj) {
        removeToManyTarget(PTF_CONFIG_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfConfig> getPtfConfigArray() {
        return (List<PtfConfig>)readProperty(PTF_CONFIG_ARRAY_PROPERTY);
    }


    public void addToPtfCruiseArray(PtfCruise obj) {
        addToManyTarget(PTF_CRUISE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfCruiseArray(PtfCruise obj) {
        removeToManyTarget(PTF_CRUISE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfCruise> getPtfCruiseArray() {
        return (List<PtfCruise>)readProperty(PTF_CRUISE_ARRAY_PROPERTY);
    }


    public void addToPtfLocArray(PtfLoc obj) {
        addToManyTarget(PTF_LOC_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfLocArray(PtfLoc obj) {
        removeToManyTarget(PTF_LOC_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfLoc> getPtfLocArray() {
        return (List<PtfLoc>)readProperty(PTF_LOC_ARRAY_PROPERTY);
    }


    public void addToPtfSensorModelArray(PtfSensorModel obj) {
        addToManyTarget(PTF_SENSOR_MODEL_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfSensorModelArray(PtfSensorModel obj) {
        removeToManyTarget(PTF_SENSOR_MODEL_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfSensorModel> getPtfSensorModelArray() {
        return (List<PtfSensorModel>)readProperty(PTF_SENSOR_MODEL_ARRAY_PROPERTY);
    }


    public void addToPtfVariableArray(PtfVariable obj) {
        addToManyTarget(PTF_VARIABLE_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfVariableArray(PtfVariable obj) {
        removeToManyTarget(PTF_VARIABLE_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<PtfVariable> getPtfVariableArray() {
        return (List<PtfVariable>)readProperty(PTF_VARIABLE_ARRAY_PROPERTY);
    }


    public void addToQcFeedbackArray(QcFeedback obj) {
        addToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromQcFeedbackArray(QcFeedback obj) {
        removeToManyTarget(QC_FEEDBACK_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<QcFeedback> getQcFeedbackArray() {
        return (List<QcFeedback>)readProperty(QC_FEEDBACK_ARRAY_PROPERTY);
    }


    public void addToSitePtfArray(SitePtf obj) {
        addToManyTarget(SITE_PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromSitePtfArray(SitePtf obj) {
        removeToManyTarget(SITE_PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SitePtf> getSitePtfArray() {
        return (List<SitePtf>)readProperty(SITE_PTF_ARRAY_PROPERTY);
    }


    public void setToDataStatus(DataStatus toDataStatus) {
        setToOneTarget(TO_DATA_STATUS_PROPERTY, toDataStatus, true);
    }

    public DataStatus getToDataStatus() {
        return (DataStatus)readProperty(TO_DATA_STATUS_PROPERTY);
    }


    public void setToEndingCause(EndingCause toEndingCause) {
        setToOneTarget(TO_ENDING_CAUSE_PROPERTY, toEndingCause, true);
    }

    public EndingCause getToEndingCause() {
        return (EndingCause)readProperty(TO_ENDING_CAUSE_PROPERTY);
    }


    public void setToObs(Obs toObs) {
        setToOneTarget(TO_OBS_PROPERTY, toObs, true);
    }

    public Obs getToObs() {
        return (Obs)readProperty(TO_OBS_PROPERTY);
    }


    public void setToProgram(Program toProgram) {
        setToOneTarget(TO_PROGRAM_PROPERTY, toProgram, true);
    }

    public Program getToProgram() {
        return (Program)readProperty(TO_PROGRAM_PROPERTY);
    }


    public void setToPtfDeployment(PtfDeployment toPtfDeployment) {
        setToOneTarget(TO_PTF_DEPLOYMENT_PROPERTY, toPtfDeployment, true);
    }

    public PtfDeployment getToPtfDeployment() {
        return (PtfDeployment)readProperty(TO_PTF_DEPLOYMENT_PROPERTY);
    }


    public void setToPtfHardware(PtfHardware toPtfHardware) {
        setToOneTarget(TO_PTF_HARDWARE_PROPERTY, toPtfHardware, true);
    }

    public PtfHardware getToPtfHardware() {
        return (PtfHardware)readProperty(TO_PTF_HARDWARE_PROPERTY);
    }


    public void setToPtfIdentifiers(PtfIdentifiers toPtfIdentifiers) {
        setToOneTarget(TO_PTF_IDENTIFIERS_PROPERTY, toPtfIdentifiers, true);
    }

    public PtfIdentifiers getToPtfIdentifiers() {
        return (PtfIdentifiers)readProperty(TO_PTF_IDENTIFIERS_PROPERTY);
    }


    public void setToPtfLoc(PtfLoc toPtfLoc) {
        setToOneTarget(TO_PTF_LOC_PROPERTY, toPtfLoc, true);
    }

    public PtfLoc getToPtfLoc() {
        return (PtfLoc)readProperty(TO_PTF_LOC_PROPERTY);
    }


    public void setToPtfModel(PtfModel toPtfModel) {
        setToOneTarget(TO_PTF_MODEL_PROPERTY, toPtfModel, true);
    }

    public PtfModel getToPtfModel() {
        return (PtfModel)readProperty(TO_PTF_MODEL_PROPERTY);
    }


    public void setToPtfStatus(PtfStatus toPtfStatus) {
        setToOneTarget(TO_PTF_STATUS_PROPERTY, toPtfStatus, true);
    }

    public PtfStatus getToPtfStatus() {
        return (PtfStatus)readProperty(TO_PTF_STATUS_PROPERTY);
    }


    public void setToRetrieval(Retrieval toRetrieval) {
        setToOneTarget(TO_RETRIEVAL_PROPERTY, toRetrieval, true);
    }

    public Retrieval getToRetrieval() {
        return (Retrieval)readProperty(TO_RETRIEVAL_PROPERTY);
    }


    public void setToSite(Site toSite) {
        setToOneTarget(TO_SITE_PROPERTY, toSite, true);
    }

    public Site getToSite() {
        return (Site)readProperty(TO_SITE_PROPERTY);
    }


    public void setToTelecom(Telecom toTelecom) {
        setToOneTarget(TO_TELECOM_PROPERTY, toTelecom, true);
    }

    public Telecom getToTelecom() {
        return (Telecom)readProperty(TO_TELECOM_PROPERTY);
    }


    public void setToTelecom1(Telecom toTelecom1) {
        setToOneTarget(TO_TELECOM1_PROPERTY, toTelecom1, true);
    }

    public Telecom getToTelecom1() {
        return (Telecom)readProperty(TO_TELECOM1_PROPERTY);
    }


    public void setToTrackingSystem(TrackingSystem toTrackingSystem) {
        setToOneTarget(TO_TRACKING_SYSTEM_PROPERTY, toTrackingSystem, true);
    }

    public TrackingSystem getToTrackingSystem() {
        return (TrackingSystem)readProperty(TO_TRACKING_SYSTEM_PROPERTY);
    }


    public void addToWeblinkArray(Weblink obj) {
        addToManyTarget(WEBLINK_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWeblinkArray(Weblink obj) {
        removeToManyTarget(WEBLINK_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Weblink> getWeblinkArray() {
        return (List<Weblink>)readProperty(WEBLINK_ARRAY_PROPERTY);
    }


    public void addToWeblinkPtfArray(WeblinkPtf obj) {
        addToManyTarget(WEBLINK_PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWeblinkPtfArray(WeblinkPtf obj) {
        removeToManyTarget(WEBLINK_PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WeblinkPtf> getWeblinkPtfArray() {
        return (List<WeblinkPtf>)readProperty(WEBLINK_PTF_ARRAY_PROPERTY);
    }


    public void addToWmoArray(Wmo obj) {
        addToManyTarget(WMO_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWmoArray(Wmo obj) {
        removeToManyTarget(WMO_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Wmo> getWmoArray() {
        return (List<Wmo>)readProperty(WMO_ARRAY_PROPERTY);
    }


}
