package jcommops.db.orm.rest.auto;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.Ptf;
import jcommops.db.orm.rest.PtfBattery;
import jcommops.db.orm.rest.PtfFirmware;
import jcommops.db.orm.rest.PtfHullType;
import jcommops.db.orm.rest.PumpType;

/**
 * Class _PtfHardware was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PtfHardware extends CayenneDataObject {

    public static final String BALLOON_SIZE_PROPERTY = "balloonSize";
    public static final String BATCH_REF_PROPERTY = "batchRef";
    public static final String DROGUE_PROPERTY = "drogue";
    public static final String MANUF_DATE_PROPERTY = "manufDate";
    public static final String MOORING_DEPTH_PROPERTY = "mooringDepth";
    public static final String MOORING_TYPE_ID_PROPERTY = "mooringTypeId";
    public static final String MOORING_WEIGHT_PROPERTY = "mooringWeight";
    public static final String SERIAL_REF_PROPERTY = "serialRef";
    public static final String SPEC_PROPERTY = "spec";
    public static final String WATCH_CIRCLE_PROPERTY = "watchCircle";
    public static final String PTF_ARRAY_PROPERTY = "ptfArray";
    public static final String TO_PTF_BATTERY_PROPERTY = "toPtfBattery";
    public static final String TO_PTF_FIRMWARE_PROPERTY = "toPtfFirmware";
    public static final String TO_PTF_FIRMWARE1_PROPERTY = "toPtfFirmware1";
    public static final String TO_PTF_HULL_TYPE_PROPERTY = "toPtfHullType";
    public static final String TO_PUMP_TYPE_PROPERTY = "toPumpType";

    public static final String ID_PK_COLUMN = "ID";

    public void setBalloonSize(BigDecimal balloonSize) {
        writeProperty(BALLOON_SIZE_PROPERTY, balloonSize);
    }
    public BigDecimal getBalloonSize() {
        return (BigDecimal)readProperty(BALLOON_SIZE_PROPERTY);
    }

    public void setBatchRef(String batchRef) {
        writeProperty(BATCH_REF_PROPERTY, batchRef);
    }
    public String getBatchRef() {
        return (String)readProperty(BATCH_REF_PROPERTY);
    }

    public void setDrogue(Integer drogue) {
        writeProperty(DROGUE_PROPERTY, drogue);
    }
    public Integer getDrogue() {
        return (Integer)readProperty(DROGUE_PROPERTY);
    }

    public void setManufDate(Date manufDate) {
        writeProperty(MANUF_DATE_PROPERTY, manufDate);
    }
    public Date getManufDate() {
        return (Date)readProperty(MANUF_DATE_PROPERTY);
    }

    public void setMooringDepth(Integer mooringDepth) {
        writeProperty(MOORING_DEPTH_PROPERTY, mooringDepth);
    }
    public Integer getMooringDepth() {
        return (Integer)readProperty(MOORING_DEPTH_PROPERTY);
    }

    public void setMooringTypeId(Integer mooringTypeId) {
        writeProperty(MOORING_TYPE_ID_PROPERTY, mooringTypeId);
    }
    public Integer getMooringTypeId() {
        return (Integer)readProperty(MOORING_TYPE_ID_PROPERTY);
    }

    public void setMooringWeight(Integer mooringWeight) {
        writeProperty(MOORING_WEIGHT_PROPERTY, mooringWeight);
    }
    public Integer getMooringWeight() {
        return (Integer)readProperty(MOORING_WEIGHT_PROPERTY);
    }

    public void setSerialRef(String serialRef) {
        writeProperty(SERIAL_REF_PROPERTY, serialRef);
    }
    public String getSerialRef() {
        return (String)readProperty(SERIAL_REF_PROPERTY);
    }

    public void setSpec(byte[] spec) {
        writeProperty(SPEC_PROPERTY, spec);
    }
    public byte[] getSpec() {
        return (byte[])readProperty(SPEC_PROPERTY);
    }

    public void setWatchCircle(Integer watchCircle) {
        writeProperty(WATCH_CIRCLE_PROPERTY, watchCircle);
    }
    public Integer getWatchCircle() {
        return (Integer)readProperty(WATCH_CIRCLE_PROPERTY);
    }

    public void addToPtfArray(Ptf obj) {
        addToManyTarget(PTF_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromPtfArray(Ptf obj) {
        removeToManyTarget(PTF_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Ptf> getPtfArray() {
        return (List<Ptf>)readProperty(PTF_ARRAY_PROPERTY);
    }


    public void setToPtfBattery(PtfBattery toPtfBattery) {
        setToOneTarget(TO_PTF_BATTERY_PROPERTY, toPtfBattery, true);
    }

    public PtfBattery getToPtfBattery() {
        return (PtfBattery)readProperty(TO_PTF_BATTERY_PROPERTY);
    }


    public void setToPtfFirmware(PtfFirmware toPtfFirmware) {
        setToOneTarget(TO_PTF_FIRMWARE_PROPERTY, toPtfFirmware, true);
    }

    public PtfFirmware getToPtfFirmware() {
        return (PtfFirmware)readProperty(TO_PTF_FIRMWARE_PROPERTY);
    }


    public void setToPtfFirmware1(PtfFirmware toPtfFirmware1) {
        setToOneTarget(TO_PTF_FIRMWARE1_PROPERTY, toPtfFirmware1, true);
    }

    public PtfFirmware getToPtfFirmware1() {
        return (PtfFirmware)readProperty(TO_PTF_FIRMWARE1_PROPERTY);
    }


    public void setToPtfHullType(PtfHullType toPtfHullType) {
        setToOneTarget(TO_PTF_HULL_TYPE_PROPERTY, toPtfHullType, true);
    }

    public PtfHullType getToPtfHullType() {
        return (PtfHullType)readProperty(TO_PTF_HULL_TYPE_PROPERTY);
    }


    public void setToPumpType(PumpType toPumpType) {
        setToOneTarget(TO_PUMP_TYPE_PROPERTY, toPumpType, true);
    }

    public PumpType getToPumpType() {
        return (PumpType)readProperty(TO_PUMP_TYPE_PROPERTY);
    }


}
