package jcommops.db.orm.rest.auto;

import org.apache.cayenne.CayenneDataObject;

import jcommops.db.orm.rest.QcFeedback;

/**
 * Class _QcFeedbackObs was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _QcFeedbackObs extends CayenneDataObject {

    public static final String TO_QC_FEEDBACK_PROPERTY = "toQcFeedback";

    public static final String OBS_ID_PK_COLUMN = "OBS_ID";
    public static final String QC_FEEDBACK_ID_PK_COLUMN = "QC_FEEDBACK_ID";

    public void setToQcFeedback(QcFeedback toQcFeedback) {
        setToOneTarget(TO_QC_FEEDBACK_PROPERTY, toQcFeedback, true);
    }

    public QcFeedback getToQcFeedback() {
        return (QcFeedback)readProperty(TO_QC_FEEDBACK_PROPERTY);
    }


}
