package org.jcommops.api.orm;

import java.math.BigDecimal;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _LineType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _LineType extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> COMMENTS = Property.create("comments", String.class);
    public static final Property<Integer> DROPS = Property.create("drops", Integer.class);
    public static final Property<Integer> HORIZ_RES_BOXES = Property.create("horizResBoxes", Integer.class);
    public static final Property<BigDecimal> HORIZ_RESOL_DEG = Property.create("horizResolDeg", BigDecimal.class);
    public static final Property<Integer> HORIZ_RESOL_HR = Property.create("horizResolHr", Integer.class);
    public static final Property<Integer> HORIZ_RESOL_KM = Property.create("horizResolKm", Integer.class);
    public static final Property<Integer> ID = Property.create("id", Integer.class);
    public static final Property<Integer> MAX_HORIZ_RES = Property.create("maxHorizRes", Integer.class);
    public static final Property<Integer> MAX_HORIZ_RES_I4 = Property.create("maxHorizResI4", Integer.class);
    public static final Property<Integer> MAX_NB_TRANS12 = Property.create("maxNbTrans12", Integer.class);
    public static final Property<Integer> MAX_NB_TRANS6 = Property.create("maxNbTrans6", Integer.class);
    public static final Property<Integer> MAX_SD_HORIZ_RES = Property.create("maxSdHorizRes", Integer.class);
    public static final Property<Integer> MAX_SD_PERIOD = Property.create("maxSdPeriod", Integer.class);
    public static final Property<Integer> MIN_HORIZ_RES = Property.create("minHorizRes", Integer.class);
    public static final Property<Integer> MIN_HORIZ_RES_I4 = Property.create("minHorizResI4", Integer.class);
    public static final Property<Integer> MIN_NB_TRANS12 = Property.create("minNbTrans12", Integer.class);
    public static final Property<Integer> MIN_NB_TRANS6 = Property.create("minNbTrans6", Integer.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> NAME_LONG = Property.create("nameLong", String.class);
    public static final Property<String> NAME_SHORT = Property.create("nameShort", String.class);
    public static final Property<Integer> PERCENT_BOXES = Property.create("percentBoxes", Integer.class);
    public static final Property<Integer> PERCENT_GOOD_TR = Property.create("percentGoodTr", Integer.class);
    public static final Property<Integer> PERIOD_TOLERANCE = Property.create("periodTolerance", Integer.class);
    public static final Property<Integer> TRANSECTS = Property.create("transects", Integer.class);
    public static final Property<List<LineSurvey>> LINE_SURVEYS = Property.create("lineSurveys", List.class);

    public void setComments(String comments) {
        writeProperty("comments", comments);
    }
    public String getComments() {
        return (String)readProperty("comments");
    }

    public void setDrops(int drops) {
        writeProperty("drops", drops);
    }
    public int getDrops() {
        Object value = readProperty("drops");
        return (value != null) ? (Integer) value : 0;
    }

    public void setHorizResBoxes(int horizResBoxes) {
        writeProperty("horizResBoxes", horizResBoxes);
    }
    public int getHorizResBoxes() {
        Object value = readProperty("horizResBoxes");
        return (value != null) ? (Integer) value : 0;
    }

    public void setHorizResolDeg(BigDecimal horizResolDeg) {
        writeProperty("horizResolDeg", horizResolDeg);
    }
    public BigDecimal getHorizResolDeg() {
        return (BigDecimal)readProperty("horizResolDeg");
    }

    public void setHorizResolHr(int horizResolHr) {
        writeProperty("horizResolHr", horizResolHr);
    }
    public int getHorizResolHr() {
        Object value = readProperty("horizResolHr");
        return (value != null) ? (Integer) value : 0;
    }

    public void setHorizResolKm(int horizResolKm) {
        writeProperty("horizResolKm", horizResolKm);
    }
    public int getHorizResolKm() {
        Object value = readProperty("horizResolKm");
        return (value != null) ? (Integer) value : 0;
    }

    public void setId(int id) {
        writeProperty("id", id);
    }
    public int getId() {
        Object value = readProperty("id");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxHorizRes(int maxHorizRes) {
        writeProperty("maxHorizRes", maxHorizRes);
    }
    public int getMaxHorizRes() {
        Object value = readProperty("maxHorizRes");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxHorizResI4(int maxHorizResI4) {
        writeProperty("maxHorizResI4", maxHorizResI4);
    }
    public int getMaxHorizResI4() {
        Object value = readProperty("maxHorizResI4");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxNbTrans12(int maxNbTrans12) {
        writeProperty("maxNbTrans12", maxNbTrans12);
    }
    public int getMaxNbTrans12() {
        Object value = readProperty("maxNbTrans12");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxNbTrans6(int maxNbTrans6) {
        writeProperty("maxNbTrans6", maxNbTrans6);
    }
    public int getMaxNbTrans6() {
        Object value = readProperty("maxNbTrans6");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxSdHorizRes(int maxSdHorizRes) {
        writeProperty("maxSdHorizRes", maxSdHorizRes);
    }
    public int getMaxSdHorizRes() {
        Object value = readProperty("maxSdHorizRes");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMaxSdPeriod(int maxSdPeriod) {
        writeProperty("maxSdPeriod", maxSdPeriod);
    }
    public int getMaxSdPeriod() {
        Object value = readProperty("maxSdPeriod");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMinHorizRes(int minHorizRes) {
        writeProperty("minHorizRes", minHorizRes);
    }
    public int getMinHorizRes() {
        Object value = readProperty("minHorizRes");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMinHorizResI4(int minHorizResI4) {
        writeProperty("minHorizResI4", minHorizResI4);
    }
    public int getMinHorizResI4() {
        Object value = readProperty("minHorizResI4");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMinNbTrans12(int minNbTrans12) {
        writeProperty("minNbTrans12", minNbTrans12);
    }
    public int getMinNbTrans12() {
        Object value = readProperty("minNbTrans12");
        return (value != null) ? (Integer) value : 0;
    }

    public void setMinNbTrans6(int minNbTrans6) {
        writeProperty("minNbTrans6", minNbTrans6);
    }
    public int getMinNbTrans6() {
        Object value = readProperty("minNbTrans6");
        return (value != null) ? (Integer) value : 0;
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNameLong(String nameLong) {
        writeProperty("nameLong", nameLong);
    }
    public String getNameLong() {
        return (String)readProperty("nameLong");
    }

    public void setNameShort(String nameShort) {
        writeProperty("nameShort", nameShort);
    }
    public String getNameShort() {
        return (String)readProperty("nameShort");
    }

    public void setPercentBoxes(int percentBoxes) {
        writeProperty("percentBoxes", percentBoxes);
    }
    public int getPercentBoxes() {
        Object value = readProperty("percentBoxes");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPercentGoodTr(int percentGoodTr) {
        writeProperty("percentGoodTr", percentGoodTr);
    }
    public int getPercentGoodTr() {
        Object value = readProperty("percentGoodTr");
        return (value != null) ? (Integer) value : 0;
    }

    public void setPeriodTolerance(int periodTolerance) {
        writeProperty("periodTolerance", periodTolerance);
    }
    public int getPeriodTolerance() {
        Object value = readProperty("periodTolerance");
        return (value != null) ? (Integer) value : 0;
    }

    public void setTransects(int transects) {
        writeProperty("transects", transects);
    }
    public int getTransects() {
        Object value = readProperty("transects");
        return (value != null) ? (Integer) value : 0;
    }

    public void addToLineSurveys(LineSurvey obj) {
        addToManyTarget("lineSurveys", obj, true);
    }
    public void removeFromLineSurveys(LineSurvey obj) {
        removeToManyTarget("lineSurveys", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<LineSurvey> getLineSurveys() {
        return (List<LineSurvey>)readProperty("lineSurveys");
    }


}
