package org.jcommops.api.orm;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ObsDataStatus was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ObsDataStatus extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String OBS_OBS_DATA_STATUSES_PROPERTY = "obsObsDataStatuses";
    public static final String OBSS_PROPERTY = "obss";

    public static final String ID_PK_COLUMN = "ID";

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToObsObsDataStatuses(ObsObsDataStatus obj) {
        addToManyTarget(OBS_OBS_DATA_STATUSES_PROPERTY, obj, true);
    }
    public void removeFromObsObsDataStatuses(ObsObsDataStatus obj) {
        removeToManyTarget(OBS_OBS_DATA_STATUSES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ObsObsDataStatus> getObsObsDataStatuses() {
        return (List<ObsObsDataStatus>)readProperty(OBS_OBS_DATA_STATUSES_PROPERTY);
    }


    public void addToObss(Obs obj) {
        addToManyTarget(OBSS_PROPERTY, obj, true);
    }
    public void removeFromObss(Obs obj) {
        removeToManyTarget(OBSS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Obs> getObss() {
        return (List<Obs>)readProperty(OBSS_PROPERTY);
    }


}
