package org.jcommops.api.orm;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _PtfRefLock was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PtfRefLock extends CayenneDataObject {

    public static final String DATE_REQUESTED_PROPERTY = "dateRequested";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String REF_PROPERTY = "ref";
    public static final String WMO_PROPERTY = "wmo";

    public static final String REF_PK_COLUMN = "REF";

    public void setDateRequested(Date dateRequested) {
        writeProperty(DATE_REQUESTED_PROPERTY, dateRequested);
    }
    public Date getDateRequested() {
        return (Date)readProperty(DATE_REQUESTED_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void setRef(String ref) {
        writeProperty(REF_PROPERTY, ref);
    }
    public String getRef() {
        return (String)readProperty(REF_PROPERTY);
    }

    public void setWmo(String wmo) {
        writeProperty(WMO_PROPERTY, wmo);
    }
    public String getWmo() {
        return (String)readProperty(WMO_PROPERTY);
    }

}
