package org.jcommops.api.orm;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ShipRecruitment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ShipRecruitment extends CayenneDataObject {

    public static final String END_DATE_PROPERTY = "endDate";
    public static final String ID_PROPERTY = "id";
    public static final String START_DATE_PROPERTY = "startDate";
    public static final String CONTACT_PROPERTY = "contact";
    public static final String PROGRAM_PROPERTY = "program";
    public static final String SHIP_PROPERTY = "ship";

    public static final String ID_PK_COLUMN = "ID";

    public void setEndDate(Date endDate) {
        writeProperty(END_DATE_PROPERTY, endDate);
    }
    public Date getEndDate() {
        return (Date)readProperty(END_DATE_PROPERTY);
    }

    public void setId(Integer id) {
        writeProperty(ID_PROPERTY, id);
    }
    public Integer getId() {
        return (Integer)readProperty(ID_PROPERTY);
    }

    public void setStartDate(Date startDate) {
        writeProperty(START_DATE_PROPERTY, startDate);
    }
    public Date getStartDate() {
        return (Date)readProperty(START_DATE_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


    public void setProgram(Program program) {
        setToOneTarget(PROGRAM_PROPERTY, program, true);
    }

    public Program getProgram() {
        return (Program)readProperty(PROGRAM_PROPERTY);
    }


    public void setShip(Ship ship) {
        setToOneTarget(SHIP_PROPERTY, ship, true);
    }

    public Ship getShip() {
        return (Ship)readProperty(SHIP_PROPERTY);
    }


}
