package org.jcommops.api.orm;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _VDbcpObsMonthly was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _VDbcpObsMonthly extends CayenneDataObject {

    public static final String COUNTRY_PROPERTY = "country";
    public static final String DELAY_PROPERTY = "delay";
    public static final String LAT_PROPERTY = "lat";
    public static final String LON_PROPERTY = "lon";
    public static final String OBS_DATE_PROPERTY = "obsDate";
    public static final String OBS_ID_PROPERTY = "obsId";
    public static final String PROGRAM_PROPERTY = "program";
    public static final String PTF_FAMILY_PROPERTY = "ptfFamily";
    public static final String PTF_MODEL_PROPERTY = "ptfModel";
    public static final String PTF_REF_PROPERTY = "ptfRef";
    public static final String PTF_TYPE_PROPERTY = "ptfType";
    public static final String TELECOM_ID_PROPERTY = "telecomId";
    public static final String TELECOM_TYPE_PROPERTY = "telecomType";
    public static final String WMO_PROPERTY = "wmo";


    public void setCountry(String country) {
        writeProperty(COUNTRY_PROPERTY, country);
    }
    public String getCountry() {
        return (String)readProperty(COUNTRY_PROPERTY);
    }

    public void setDelay(Integer delay) {
        writeProperty(DELAY_PROPERTY, delay);
    }
    public Integer getDelay() {
        return (Integer)readProperty(DELAY_PROPERTY);
    }

    public void setLat(BigDecimal lat) {
        writeProperty(LAT_PROPERTY, lat);
    }
    public BigDecimal getLat() {
        return (BigDecimal)readProperty(LAT_PROPERTY);
    }

    public void setLon(BigDecimal lon) {
        writeProperty(LON_PROPERTY, lon);
    }
    public BigDecimal getLon() {
        return (BigDecimal)readProperty(LON_PROPERTY);
    }

    public void setObsDate(Date obsDate) {
        writeProperty(OBS_DATE_PROPERTY, obsDate);
    }
    public Date getObsDate() {
        return (Date)readProperty(OBS_DATE_PROPERTY);
    }

    public void setObsId(Integer obsId) {
        writeProperty(OBS_ID_PROPERTY, obsId);
    }
    public Integer getObsId() {
        return (Integer)readProperty(OBS_ID_PROPERTY);
    }

    public void setProgram(String program) {
        writeProperty(PROGRAM_PROPERTY, program);
    }
    public String getProgram() {
        return (String)readProperty(PROGRAM_PROPERTY);
    }

    public void setPtfFamily(String ptfFamily) {
        writeProperty(PTF_FAMILY_PROPERTY, ptfFamily);
    }
    public String getPtfFamily() {
        return (String)readProperty(PTF_FAMILY_PROPERTY);
    }

    public void setPtfModel(String ptfModel) {
        writeProperty(PTF_MODEL_PROPERTY, ptfModel);
    }
    public String getPtfModel() {
        return (String)readProperty(PTF_MODEL_PROPERTY);
    }

    public void setPtfRef(String ptfRef) {
        writeProperty(PTF_REF_PROPERTY, ptfRef);
    }
    public String getPtfRef() {
        return (String)readProperty(PTF_REF_PROPERTY);
    }

    public void setPtfType(String ptfType) {
        writeProperty(PTF_TYPE_PROPERTY, ptfType);
    }
    public String getPtfType() {
        return (String)readProperty(PTF_TYPE_PROPERTY);
    }

    public void setTelecomId(String telecomId) {
        writeProperty(TELECOM_ID_PROPERTY, telecomId);
    }
    public String getTelecomId() {
        return (String)readProperty(TELECOM_ID_PROPERTY);
    }

    public void setTelecomType(String telecomType) {
        writeProperty(TELECOM_TYPE_PROPERTY, telecomType);
    }
    public String getTelecomType() {
        return (String)readProperty(TELECOM_TYPE_PROPERTY);
    }

    public void setWmo(String wmo) {
        writeProperty(WMO_PROPERTY, wmo);
    }
    public String getWmo() {
        return (String)readProperty(WMO_PROPERTY);
    }

}
