package org.jcommops.api.orm;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _WebConnection was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebConnection extends CayenneDataObject {

    public static final String IDENTIFIER_PROPERTY = "identifier";
    public static final String LAST_LOG_DATE_PROPERTY = "lastLogDate";
    public static final String TOKEN_PROPERTY = "token";
    public static final String CONTACT_PROPERTY = "contact";

    public static final String IDENTIFIER_PK_COLUMN = "IDENTIFIER";

    public void setIdentifier(String identifier) {
        writeProperty(IDENTIFIER_PROPERTY, identifier);
    }
    public String getIdentifier() {
        return (String)readProperty(IDENTIFIER_PROPERTY);
    }

    public void setLastLogDate(Date lastLogDate) {
        writeProperty(LAST_LOG_DATE_PROPERTY, lastLogDate);
    }
    public Date getLastLogDate() {
        return (Date)readProperty(LAST_LOG_DATE_PROPERTY);
    }

    public void setToken(String token) {
        writeProperty(TOKEN_PROPERTY, token);
    }
    public String getToken() {
        return (String)readProperty(TOKEN_PROPERTY);
    }

    public void setContact(Contact contact) {
        setToOneTarget(CONTACT_PROPERTY, contact, true);
    }

    public Contact getContact() {
        return (Contact)readProperty(CONTACT_PROPERTY);
    }


}
