package org.jcommops.api.orm;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _WebMetric was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebMetric extends CayenneDataObject {

    public static final String METHOD_PROPERTY = "method";
    public static final String NAME_PROPERTY = "name";
    public static final String WEB_METRIC_MASTER_PROG_ARRAY_PROPERTY = "webMetricMasterProgArray";

    public static final String ID_PK_COLUMN = "ID";

    public void setMethod(String method) {
        writeProperty(METHOD_PROPERTY, method);
    }
    public String getMethod() {
        return (String)readProperty(METHOD_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void addToWebMetricMasterProgArray(WebMetricMasterProg obj) {
        addToManyTarget(WEB_METRIC_MASTER_PROG_ARRAY_PROPERTY, obj, true);
    }
    public void removeFromWebMetricMasterProgArray(WebMetricMasterProg obj) {
        removeToManyTarget(WEB_METRIC_MASTER_PROG_ARRAY_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<WebMetricMasterProg> getWebMetricMasterProgArray() {
        return (List<WebMetricMasterProg>)readProperty(WEB_METRIC_MASTER_PROG_ARRAY_PROPERTY);
    }


}
