package org.oceanops.api.orm;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _WebPtfVisits was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _WebPtfVisits extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String PTF_REF_PK_COLUMN = "PTF_REF";
    public static final String VISIT_COUNT_PK_COLUMN = "VISIT_COUNT";

    public static final Property<String> PTF_REF = Property.create("ptfRef", String.class);
    public static final Property<BigDecimal> VISIT_COUNT = Property.create("visitCount", BigDecimal.class);

    public void setPtfRef(String ptfRef) {
        writeProperty("ptfRef", ptfRef);
    }
    public String getPtfRef() {
        return (String)readProperty("ptfRef");
    }

    public void setVisitCount(BigDecimal visitCount) {
        writeProperty("visitCount", visitCount);
    }
    public BigDecimal getVisitCount() {
        return (BigDecimal)readProperty("visitCount");
    }

}
