package org.oceanops.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.oceanops.orm.PtfAncillaryDeviceName;
import org.oceanops.orm.PtfModel;

/**
 * Class _PtfAncillaryDeviceVersion was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PtfAncillaryDeviceVersion extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> VERSION = PropertyFactory.createString("version", String.class);
    public static final EntityProperty<PtfAncillaryDeviceName> PTF_ANCILLARY_DEVICE_NAME = PropertyFactory.createEntity("ptfAncillaryDeviceName", PtfAncillaryDeviceName.class);
    public static final EntityProperty<PtfModel> PTF_MODEL = PropertyFactory.createEntity("ptfModel", PtfModel.class);

    protected String version;

    protected Object ptfAncillaryDeviceName;
    protected Object ptfModel;

    public void setVersion(String version) {
        beforePropertyWrite("version", this.version, version);
        this.version = version;
    }

    public String getVersion() {
        beforePropertyRead("version");
        return this.version;
    }

    public void setPtfAncillaryDeviceName(PtfAncillaryDeviceName ptfAncillaryDeviceName) {
        setToOneTarget("ptfAncillaryDeviceName", ptfAncillaryDeviceName, true);
    }

    public PtfAncillaryDeviceName getPtfAncillaryDeviceName() {
        return (PtfAncillaryDeviceName)readProperty("ptfAncillaryDeviceName");
    }

    public void setPtfModel(PtfModel ptfModel) {
        setToOneTarget("ptfModel", ptfModel, true);
    }

    public PtfModel getPtfModel() {
        return (PtfModel)readProperty("ptfModel");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "version":
                return this.version;
            case "ptfAncillaryDeviceName":
                return this.ptfAncillaryDeviceName;
            case "ptfModel":
                return this.ptfModel;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "version":
                this.version = (String)val;
                break;
            case "ptfAncillaryDeviceName":
                this.ptfAncillaryDeviceName = val;
                break;
            case "ptfModel":
                this.ptfModel = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.version);
        out.writeObject(this.ptfAncillaryDeviceName);
        out.writeObject(this.ptfModel);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.version = (String)in.readObject();
        this.ptfAncillaryDeviceName = in.readObject();
        this.ptfModel = in.readObject();
    }

}
