package org.oceanops.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;
import org.apache.cayenne.value.Wkt;
import org.oceanops.orm.AgencySiteRole;
import org.oceanops.orm.ContactSiteRole;
import org.oceanops.orm.NetworkSite;
import org.oceanops.orm.SiteFamily;
import org.oceanops.orm.SitePtf;
import org.oceanops.orm.SiteStatus;

/**
 * Class _Site was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Site extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "ID";

    public static final StringProperty<String> DESCRIPTION = PropertyFactory.createString("description", String.class);
    public static final BaseProperty<Wkt> GEOM = PropertyFactory.createBase("geom", Wkt.class);
    public static final NumericProperty<Integer> ID = PropertyFactory.createNumeric("id", Integer.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final StringProperty<String> NAME_SHORT = PropertyFactory.createString("nameShort", String.class);
    public static final NumericProperty<Integer> TARGETED_OCCUPATION = PropertyFactory.createNumeric("targetedOccupation", Integer.class);
    public static final ListProperty<AgencySiteRole> AGENCY_SITE_ROLES = PropertyFactory.createList("agencySiteRoles", AgencySiteRole.class);
    public static final ListProperty<ContactSiteRole> CONTACT_SITE_ROLES = PropertyFactory.createList("contactSiteRoles", ContactSiteRole.class);
    public static final ListProperty<NetworkSite> NETWORK_SITES = PropertyFactory.createList("networkSites", NetworkSite.class);
    public static final EntityProperty<SiteFamily> SITE_FAMILY = PropertyFactory.createEntity("siteFamily", SiteFamily.class);
    public static final ListProperty<SitePtf> SITE_PTFS = PropertyFactory.createList("sitePtfs", SitePtf.class);
    public static final EntityProperty<SiteStatus> STATUS = PropertyFactory.createEntity("status", SiteStatus.class);

    protected String description;
    protected Wkt geom;
    protected Integer id;
    protected String name;
    protected String nameShort;
    protected Integer targetedOccupation;

    protected Object agencySiteRoles;
    protected Object contactSiteRoles;
    protected Object networkSites;
    protected Object siteFamily;
    protected Object sitePtfs;
    protected Object status;

    public void setDescription(String description) {
        beforePropertyWrite("description", this.description, description);
        this.description = description;
    }

    public String getDescription() {
        beforePropertyRead("description");
        return this.description;
    }

    public void setGeom(Wkt geom) {
        beforePropertyWrite("geom", this.geom, geom);
        this.geom = geom;
    }

    public Wkt getGeom() {
        beforePropertyRead("geom");
        return this.geom;
    }

    public void setId(Integer id) {
        beforePropertyWrite("id", this.id, id);
        this.id = id;
    }

    public Integer getId() {
        beforePropertyRead("id");
        return this.id;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void setNameShort(String nameShort) {
        beforePropertyWrite("nameShort", this.nameShort, nameShort);
        this.nameShort = nameShort;
    }

    public String getNameShort() {
        beforePropertyRead("nameShort");
        return this.nameShort;
    }

    public void setTargetedOccupation(Integer targetedOccupation) {
        beforePropertyWrite("targetedOccupation", this.targetedOccupation, targetedOccupation);
        this.targetedOccupation = targetedOccupation;
    }

    public Integer getTargetedOccupation() {
        beforePropertyRead("targetedOccupation");
        return this.targetedOccupation;
    }

    public void addToAgencySiteRoles(AgencySiteRole obj) {
        addToManyTarget("agencySiteRoles", obj, true);
    }

    public void removeFromAgencySiteRoles(AgencySiteRole obj) {
        removeToManyTarget("agencySiteRoles", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<AgencySiteRole> getAgencySiteRoles() {
        return (List<AgencySiteRole>)readProperty("agencySiteRoles");
    }

    public void addToContactSiteRoles(ContactSiteRole obj) {
        addToManyTarget("contactSiteRoles", obj, true);
    }

    public void removeFromContactSiteRoles(ContactSiteRole obj) {
        removeToManyTarget("contactSiteRoles", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<ContactSiteRole> getContactSiteRoles() {
        return (List<ContactSiteRole>)readProperty("contactSiteRoles");
    }

    public void addToNetworkSites(NetworkSite obj) {
        addToManyTarget("networkSites", obj, true);
    }

    public void removeFromNetworkSites(NetworkSite obj) {
        removeToManyTarget("networkSites", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<NetworkSite> getNetworkSites() {
        return (List<NetworkSite>)readProperty("networkSites");
    }

    public void setSiteFamily(SiteFamily siteFamily) {
        setToOneTarget("siteFamily", siteFamily, true);
    }

    public SiteFamily getSiteFamily() {
        return (SiteFamily)readProperty("siteFamily");
    }

    public void addToSitePtfs(SitePtf obj) {
        addToManyTarget("sitePtfs", obj, true);
    }

    public void removeFromSitePtfs(SitePtf obj) {
        removeToManyTarget("sitePtfs", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<SitePtf> getSitePtfs() {
        return (List<SitePtf>)readProperty("sitePtfs");
    }

    public void setStatus(SiteStatus status) {
        setToOneTarget("status", status, true);
    }

    public SiteStatus getStatus() {
        return (SiteStatus)readProperty("status");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "description":
                return this.description;
            case "geom":
                return this.geom;
            case "id":
                return this.id;
            case "name":
                return this.name;
            case "nameShort":
                return this.nameShort;
            case "targetedOccupation":
                return this.targetedOccupation;
            case "agencySiteRoles":
                return this.agencySiteRoles;
            case "contactSiteRoles":
                return this.contactSiteRoles;
            case "networkSites":
                return this.networkSites;
            case "siteFamily":
                return this.siteFamily;
            case "sitePtfs":
                return this.sitePtfs;
            case "status":
                return this.status;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "description":
                this.description = (String)val;
                break;
            case "geom":
                this.geom = (Wkt)val;
                break;
            case "id":
                this.id = (Integer)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "nameShort":
                this.nameShort = (String)val;
                break;
            case "targetedOccupation":
                this.targetedOccupation = (Integer)val;
                break;
            case "agencySiteRoles":
                this.agencySiteRoles = val;
                break;
            case "contactSiteRoles":
                this.contactSiteRoles = val;
                break;
            case "networkSites":
                this.networkSites = val;
                break;
            case "siteFamily":
                this.siteFamily = val;
                break;
            case "sitePtfs":
                this.sitePtfs = val;
                break;
            case "status":
                this.status = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.description);
        out.writeObject(this.geom);
        out.writeObject(this.id);
        out.writeObject(this.name);
        out.writeObject(this.nameShort);
        out.writeObject(this.targetedOccupation);
        out.writeObject(this.agencySiteRoles);
        out.writeObject(this.contactSiteRoles);
        out.writeObject(this.networkSites);
        out.writeObject(this.siteFamily);
        out.writeObject(this.sitePtfs);
        out.writeObject(this.status);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.description = (String)in.readObject();
        this.geom = (Wkt)in.readObject();
        this.id = (Integer)in.readObject();
        this.name = (String)in.readObject();
        this.nameShort = (String)in.readObject();
        this.targetedOccupation = (Integer)in.readObject();
        this.agencySiteRoles = in.readObject();
        this.contactSiteRoles = in.readObject();
        this.networkSites = in.readObject();
        this.siteFamily = in.readObject();
        this.sitePtfs = in.readObject();
        this.status = in.readObject();
    }

}
