package org.oceanops.orm.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.oceanops.orm.Ptf;
import org.oceanops.orm.Site;

/**
 * Class _SitePtf was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SitePtf extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String PTF_ID_PK_COLUMN = "PTF_ID";
    public static final String SITE_ID_PK_COLUMN = "SITE_ID";

    public static final NumericProperty<Integer> PTF_ID = PropertyFactory.createNumeric("ptfId", Integer.class);
    public static final NumericProperty<Integer> SITE_ID = PropertyFactory.createNumeric("siteId", Integer.class);
    public static final EntityProperty<Ptf> PTF = PropertyFactory.createEntity("ptf", Ptf.class);
    public static final EntityProperty<Site> SITE = PropertyFactory.createEntity("site", Site.class);

    protected Integer ptfId;
    protected Integer siteId;

    protected Object ptf;
    protected Object site;

    public void setPtfId(Integer ptfId) {
        beforePropertyWrite("ptfId", this.ptfId, ptfId);
        this.ptfId = ptfId;
    }

    public Integer getPtfId() {
        beforePropertyRead("ptfId");
        return this.ptfId;
    }

    public void setSiteId(Integer siteId) {
        beforePropertyWrite("siteId", this.siteId, siteId);
        this.siteId = siteId;
    }

    public Integer getSiteId() {
        beforePropertyRead("siteId");
        return this.siteId;
    }

    public void setPtf(Ptf ptf) {
        setToOneTarget("ptf", ptf, true);
    }

    public Ptf getPtf() {
        return (Ptf)readProperty("ptf");
    }

    public void setSite(Site site) {
        setToOneTarget("site", site, true);
    }

    public Site getSite() {
        return (Site)readProperty("site");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "ptfId":
                return this.ptfId;
            case "siteId":
                return this.siteId;
            case "ptf":
                return this.ptf;
            case "site":
                return this.site;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "ptfId":
                this.ptfId = (Integer)val;
                break;
            case "siteId":
                this.siteId = (Integer)val;
                break;
            case "ptf":
                this.ptf = val;
                break;
            case "site":
                this.site = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.ptfId);
        out.writeObject(this.siteId);
        out.writeObject(this.ptf);
        out.writeObject(this.site);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.ptfId = (Integer)in.readObject();
        this.siteId = (Integer)in.readObject();
        this.ptf = in.readObject();
        this.site = in.readObject();
    }

}
